// ESLint 10 flat config for the whole monorepo.
import js from '@eslint/js';
import { defineConfig, globalIgnores } from 'eslint/config';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import eslintConfigPrettier from 'eslint-config-prettier';
import globals from 'globals';

export default defineConfig([
  globalIgnores([
    '**/dist/**',
    '**/build/**',
    '**/coverage/**',
    '**/.turbo/**',
    '**/node_modules/**',
    '**/src/generated/**',
    '**/src/generated-es/**',
    '.mise/**',
    // Generated by site/scripts/sync-docs.mjs (markdown mirror + VitePress build output),
    // not source — see site/package.json build/dev scripts.
    'site/docs/**',
    'site/.vitepress/cache/**',
    'site/.vitepress/dist/**',
  ]),
  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    ignores: ['vitest.config.ts'],
    extends: [js.configs.recommended, tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: {
          // Every package's own build/test config files (vitest.config.ts,
          // vitest.config.mts, vitest.integration.config.mts, tsup.config.ts, ...) —
          // letting typescript-eslint fall back to its default,
          // tsconfig-less program for these means each package's tsconfig.json doesn't
          // have to `include` them just to keep typed linting from erroring (B-005).
          // `**` is disallowed here (typescript-eslint caps default-project matching to
          // bounded globs to avoid every file in the repo silently falling back to it —
          // https://tseslint.com/allowdefaultproject-glob-too-wide), so this is spelled
          // out one path segment per depth instead of a single recursive pattern.
          // Scoped to the packages whose tsconfig.json no longer `include`s its own
          // config files (B-005) — a file can't appear both here *and* in a tsconfig's
          // `include`, so packages not listed here (apps/tui, packages/proto,
          // packages/media) keep including their config files in tsconfig.json until
          // someone applies the same change there.
          allowDefaultProject: [
            'apps/admin/*.config.{ts,mts,cts}',
            'apps/server/*.config.{ts,mts,cts}',
            'apps/worker/*.config.{ts,mts,cts}',
            'packages/config/*.config.{ts,mts,cts}',
            'packages/database/*.config.{ts,mts,cts}',
            'packages/harness/*.config.{ts,mts,cts}',
            'packages/markup/*.config.{ts,mts,cts}',
            'packages/observability/*.config.{ts,mts,cts}',
            'packages/testkit/*.config.{ts,mts,cts}',
            'packages/terminal-media/*.config.{ts,mts,cts}',
          ],
          // apps/web/tsconfig.json already includes vite.config.ts/vitest.config.ts
          // itself (same pattern as apps/tui), so it doesn't need an entry here.
          // Default cap is 8; the explicitly listed package configs above contribute 20
          // matching files. The root Vitest config is linted below without falling back to
          // a default project, so this intentionally remains a tight fixed bound.
          maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING: 20,
        },
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.node },
    },
    rules: {
      // Spec §7/§154: no `any`, prefer `unknown` for untrusted data.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': [
        'error',
        { checksVoidReturn: { attributes: false } },
      ],
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/ban-ts-comment': [
        'error',
        { 'ts-expect-error': 'allow-with-description' },
      ],
      'no-empty': ['error', { allowEmptyCatch: false }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    // This root orchestration config intentionally has no owning tsconfig. Its imports are
    // type-safe at build/runtime, but it does not need a tsconfig-less typed program; keeping
    // it out of allowDefaultProject preserves the bounded package-config lint cost above.
    files: ['vitest.config.ts'],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    languageOptions: {
      globals: { ...globals.node },
    },
  },
  {
    // Bench CLIs print their measurements to stdout — that output IS the artifact (P19-007,
    // packages/bench). Same allowance the test files get; warn/error stay allowed app-wide.
    files: ['packages/bench/**/*.ts'],
    rules: {
      'no-console': 'off',
    },
  },
  {
    // NestJS packages rely on decorators + DI; relax a couple of rules that fight the framework.
    files: ['apps/server/**', 'apps/worker/**', 'apps/admin/**', 'packages/database/**'],
    rules: {
      '@typescript-eslint/no-extraneous-class': 'off',
    },
  },
  {
    // Ink / React 19 client.
    files: ['apps/tui/**/*.{ts,tsx}', 'packages/terminal-media/**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat.recommended],
    rules: {
      // The TUI writes to stdout deliberately via Ink; direct console use corrupts the screen.
      'no-console': 'error',
    },
  },
  {
    // Vite/React 19 web client — runs in the browser, not Node.
    files: ['apps/web/**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat.recommended],
    languageOptions: {
      globals: { ...globals.browser },
    },
  },
  {
    files: ['**/*.{test,spec}.{ts,tsx}', 'packages/testkit/**'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      'no-console': 'off',
    },
  },
  {
    files: ['**/sw.js', '**/service-worker.js'],
    languageOptions: { globals: { ...globals.serviceworker } },
  },
  {
    files: ['**/*.{js,mjs,cjs}'],
    extends: [js.configs.recommended],
    languageOptions: { globals: { ...globals.node } },
  },
  eslintConfigPrettier,
]);
