/**
 * `@patches/proto` — the client/server contract.
 *
 * The generated protobuf **types** are re-exported here with `export type`, so
 * importing this entry point never pulls `@nestjs/microservices` (or Nest's DI
 * runtime) into the ESM Ink TUI. Code that needs the generated Nest decorators —
 * i.e. only `apps/server` — imports them from `@patches/proto/nest`.
 */

// Explicit type re-exports rather than `export type *`: the generated modules
// each declare `protobufPackage`/`PATCHES_V1_PACKAGE_NAME`, and star-exporting
// several of them would make those names ambiguous.
export type { Timestamp } from './generated/google/protobuf/timestamp.js';
export type { PageInfo } from './generated/patches/v1/common.js';
export type {
  GetServerInfoRequest,
  GetServerInfoResponse,
  PingRequest,
  PingResponse,
  SystemServiceClient,
  SystemServiceController,
} from './generated/patches/v1/system.js';
export type {
  Actor,
  ActorCounts,
  ActorFlair,
  ActorServiceClient,
  ActorServiceController,
  GetActorByHandleRequest,
  GetActorByHandleResponse,
  GetActorRequest,
  GetActorResponse,
  ListFollowersRequest,
  ListFollowersResponse,
  ListFollowingRequest,
  ListFollowingResponse,
  MediaRef,
  Nameplate,
  ResolveActorRequest,
  ResolveActorResponse,
  SearchActorsRequest,
  SearchActorsResponse,
  UpdateProfileRequest,
  UpdateProfileResponse,
} from './generated/patches/v1/actors.js';
export type {
  AddCredentialRequest,
  AddCredentialResponse,
  AuthServiceClient,
  AuthServiceController,
  BeginGitHubLoginRequest,
  BeginGitHubLoginResponse,
  BeginSshEnrollmentRequest,
  BeginSshEnrollmentResponse,
  BeginSshLoginRequest,
  BeginSshLoginResponse,
  CompleteSshLoginRequest,
  CompleteSshLoginResponse,
  Credential,
  GetCurrentSessionRequest,
  GetCurrentSessionResponse,
  ListCredentialsRequest,
  ListCredentialsResponse,
  LoginRequest,
  LoginResponse,
  LogoutAllSessionsRequest,
  LogoutAllSessionsResponse,
  LogoutRequest,
  LogoutResponse,
  PollGitHubLoginRequest,
  PollGitHubLoginResponse,
  RefreshSessionRequest,
  RefreshSessionResponse,
  RegisterRequest,
  RegisterResponse,
  RequestPasswordResetRequest,
  RequestPasswordResetResponse,
  ResendVerificationRequest,
  ResendVerificationResponse,
  ResetPasswordRequest,
  ResetPasswordResponse,
  RevokeCredentialRequest,
  RevokeCredentialResponse,
  Session,
  SshEnrollmentProof,
  VerifyEmailRequest,
  VerifyEmailResponse,
} from './generated/patches/v1/auth.js';
// Enum *types* only here — `export type` is erased at compile time, unlike a value export
// (see `enums.ts` for why the runtime values come from a hand-mirrored module instead).
export type { CredentialType, GitHubLoginStatus } from './generated/patches/v1/auth.js';
export type {
  ListActorPostsRequest,
  ListActorPostsResponse,
  ListCommunityFeedRequest,
  ListCommunityFeedResponse,
  ListHomeFeedRequest,
  ListHomeFeedResponse,
  ListLocalFeedRequest,
  ListLocalFeedResponse,
  ListTagFeedRequest,
  ListTagFeedResponse,
  FeedServiceClient,
  FeedServiceController,
} from './generated/patches/v1/feeds.js';
export type {
  CreatePostRequest,
  CreatePostResponse,
  DeletePostRequest,
  DeletePostResponse,
  EditPostRequest,
  EditPostResponse,
  FilteredByHint,
  GetPostRequest,
  GetPostResponse,
  ListPostEditsRequest,
  ListPostEditsResponse,
  ListRepliesRequest,
  ListRepliesResponse,
  MediaAttachment,
  PinPostRequest,
  PinPostResponse,
  Post,
  PostCounts,
  PostEdit,
  PostServiceClient,
  PostServiceController,
  PostViewerState,
  SearchPostsRequest,
  SearchPostsResponse,
  UnpinPostRequest,
  UnpinPostResponse,
} from './generated/patches/v1/posts.js';
export type {
  FilteredByProvenance,
  PostType,
  PostVisibility,
  QuotePolicy,
} from './generated/patches/v1/posts.js';
export type {
  AcceptFollowRequestRequest,
  AcceptFollowRequestResponse,
  FollowActorRequest,
  FollowActorResponse,
  FollowRequest,
  GetRelationshipRequest,
  GetRelationshipResponse,
  ListFollowRequestsRequest,
  ListFollowRequestsResponse,
  ListMutualFollowsRequest,
  ListMutualFollowsResponse,
  RejectFollowRequestRequest,
  RejectFollowRequestResponse,
  Relationship,
  SocialGraphServiceClient,
  SocialGraphServiceController,
  UnfollowActorRequest,
  UnfollowActorResponse,
} from './generated/patches/v1/social_graph.js';
export type { FollowState } from './generated/patches/v1/social_graph.js';
export type {
  DomainPolicyEntry,
  GetNodeInfoRequest,
  GetNodeInfoResponse,
  GetNodePolicyRequest,
  GetNodePolicyResponse,
  NodeLimits,
  NodePolicy,
  NodeServiceClient,
  NodeServiceController,
  RetentionWindows,
  SocialCapabilities,
} from './generated/patches/v1/node.js';
export type {
  DomainPolicyAction,
  FederationStance,
  RegistrationMode,
} from './generated/patches/v1/node.js';
export type {
  BookmarkPostRequest,
  BookmarkPostResponse,
  ListBookmarksRequest,
  ListBookmarksResponse,
  ListPostLikersRequest,
  ListPostLikersResponse,
  ListPostRepostersRequest,
  ListPostRepostersResponse,
  LikePostRequest,
  LikePostResponse,
  ReactionServiceClient,
  ReactionServiceController,
  RepostPostRequest,
  RepostPostResponse,
  UnbookmarkPostRequest,
  UnbookmarkPostResponse,
  UnlikePostRequest,
  UnlikePostResponse,
  UnrepostPostRequest,
  UnrepostPostResponse,
} from './generated/patches/v1/reactions.js';
export type {
  GetUnreadCountRequest,
  GetUnreadCountResponse,
  ListNotificationsRequest,
  ListNotificationsResponse,
  MarkNotificationsReadRequest,
  MarkNotificationsReadResponse,
  Notification,
  NotificationServiceClient,
  NotificationServiceController,
} from './generated/patches/v1/notifications.js';
export type { NotificationType } from './generated/patches/v1/notifications.js';
export type {
  BlockActorRequest,
  BlockActorResponse,
  ListBlocksRequest,
  ListBlocksResponse,
  ListModerationLogRequest,
  ListModerationLogResponse,
  ListMutesRequest,
  ListMutesResponse,
  ListMyModerationNoticesRequest,
  ListMyModerationNoticesResponse,
  ModerationLogEntry,
  ModerationNotice,
  ModerationServiceClient,
  ModerationServiceController,
  MuteActorRequest,
  MuteActorResponse,
  ReportActorRequest,
  ReportActorResponse,
  ReportMessageRequest,
  ReportMessageResponse,
  ReportPostRequest,
  ReportPostResponse,
  UnblockActorRequest,
  UnblockActorResponse,
  UnmuteActorRequest,
  UnmuteActorResponse,
} from './generated/patches/v1/moderation.js';
export type {
  ModerationActionType,
  ModerationLogSubjectKind,
  ModerationReasonCategory,
  ReportReason,
} from './generated/patches/v1/moderation.js';
export type {
  BeginMediaUploadRequest,
  BeginMediaUploadResponse,
  FinalizeMediaUploadRequest,
  FinalizeMediaUploadResponse,
  GetMediaDownloadRequest,
  GetMediaDownloadResponse,
  MediaServiceClient,
  MediaServiceController,
} from './generated/patches/v1/media.js';
export type { MediaStatus } from './generated/patches/v1/media.js';
export type {
  GetPageRequest,
  GetPageResponse,
  GuestbookEntry,
  ListGuestbookRequest,
  ListGuestbookResponse,
  ListPageRevisionsRequest,
  ListPageRevisionsResponse,
  PageRevisionSummary,
  PageServiceClient,
  PageServiceController,
  PageTheme,
  RemoveGuestbookEntryRequest,
  RemoveGuestbookEntryResponse,
  ReportGuestbookEntryRequest,
  ReportGuestbookEntryResponse,
  SignGuestbookRequest,
  SignGuestbookResponse,
  UpdatePageRequest,
  UpdatePageResponse,
} from './generated/patches/v1/pages.js';
export type {
  BanFromCommunityRequest,
  BanFromCommunityResponse,
  Community,
  CommunityCounts,
  CommunityInvite,
  CommunityMember,
  CommunityServiceClient,
  CommunityServiceController,
  CreateCommunityRequest,
  CreateCommunityResponse,
  GetCommunityRequest,
  GetCommunityResponse,
  InviteToCommunityRequest,
  InviteToCommunityResponse,
  JoinCommunityRequest,
  JoinCommunityResponse,
  LeaveCommunityRequest,
  LeaveCommunityResponse,
  ListCommunitiesRequest,
  ListCommunitiesResponse,
  ListCommunityMembersRequest,
  ListCommunityMembersResponse,
  RemovePostFromCommunityRequest,
  RemovePostFromCommunityResponse,
  RespondToCommunityInviteRequest,
  RespondToCommunityInviteResponse,
  SetCommunityRoleRequest,
  SetCommunityRoleResponse,
  UpdateCommunityRequest,
  UpdateCommunityResponse,
} from './generated/patches/v1/communities.js';
export type { CommunityInviteStatus, CommunityRole } from './generated/patches/v1/communities.js';
export type {
  Conversation,
  ConversationMember,
  CreateConversationRequest,
  CreateConversationResponse,
  DeleteMessageRequest,
  DeleteMessageResponse,
  DirectMessageServiceClient,
  DirectMessageServiceController,
  GetConversationRequest,
  GetConversationResponse,
  LeaveConversationRequest,
  LeaveConversationResponse,
  ListConversationsRequest,
  ListConversationsResponse,
  ListMessageRequestsRequest,
  ListMessageRequestsResponse,
  ListMessagesRequest,
  ListMessagesResponse,
  MarkConversationReadRequest,
  MarkConversationReadResponse,
  Message,
  MessageRequest,
  RespondToMessageRequestRequest,
  RespondToMessageRequestResponse,
  SendMessageRequest,
  SendMessageResponse,
} from './generated/patches/v1/messages.js';
export type { ConversationKind, MessageRequestStatus } from './generated/patches/v1/messages.js';
export type {
  ListMutedTagsRequest,
  ListMutedTagsResponse,
  MuteTagRequest,
  MuteTagResponse,
  SearchTagsRequest,
  SearchTagsResponse,
  Tag,
  TagServiceClient,
  TagServiceController,
  UnmuteTagRequest,
  UnmuteTagResponse,
} from './generated/patches/v1/tags.js';
export type {
  CreateFilterRequest,
  CreateFilterResponse,
  DeleteFilterRequest,
  DeleteFilterResponse,
  ExportFiltersRequest,
  ExportFiltersResponse,
  Filter,
  FilterServiceClient,
  FilterServiceController,
  FilterTerm,
  FilterTermInput,
  ImportFiltersRequest,
  ImportFiltersResponse,
  ListFiltersRequest,
  ListFiltersResponse,
  UpdateFilterRequest,
  UpdateFilterResponse,
} from './generated/patches/v1/filters.js';
export type { FilterAction, FilterScope, FilterTermKind } from './generated/patches/v1/filters.js';
export type {
  DeleteFilterListRequest,
  DeleteFilterListResponse,
  FilterList,
  FilterListEntry,
  FilterListServiceClient,
  FilterListServiceController,
  FilterListSubscription,
  GetFilterListRequest,
  GetFilterListResponse,
  ListFilterListEntriesRequest,
  ListFilterListEntriesResponse,
  ListFilterListsRequest,
  ListFilterListsResponse,
  ListFilterListSubscriptionsRequest,
  ListFilterListSubscriptionsResponse,
  PublishFilterListRequest,
  PublishFilterListResponse,
  SetFilterListEntryExceptionRequest,
  SetFilterListEntryExceptionResponse,
  SubscribeFilterListRequest,
  SubscribeFilterListResponse,
  UnsubscribeFilterListRequest,
  UnsubscribeFilterListResponse,
  UpdateFilterListRequest,
  UpdateFilterListResponse,
} from './generated/patches/v1/filter_lists.js';
export type {
  ApplyLabelRequest,
  ApplyLabelResponse,
  CreateLabelerRequest,
  CreateLabelerResponse,
  Label,
  Labeler,
  LabelServiceClient,
  LabelServiceController,
  LabelVocabularyEntry,
  GetLabelerRequest,
  GetLabelerResponse,
  ListLabelersRequest,
  ListLabelersResponse,
  ListLabelsOnSubjectRequest,
  ListLabelsOnSubjectResponse,
  RetractLabelRequest,
  RetractLabelResponse,
  SetLabelerSubscriptionActionRequest,
  SetLabelerSubscriptionActionResponse,
  SubscribeLabelerRequest,
  SubscribeLabelerResponse,
  UnsubscribeLabelerRequest,
  UnsubscribeLabelerResponse,
} from './generated/patches/v1/labels.js';
export type { LabelAction } from './generated/patches/v1/labels.js';
export type {
  Appeal,
  AppealServiceClient,
  AppealServiceController,
  CreateAppealRequest,
  CreateAppealResponse,
  GetAppealRequest,
  GetAppealResponse,
  ListMyAppealsRequest,
  ListMyAppealsResponse,
} from './generated/patches/v1/appeals.js';
export type { AppealStatus } from './generated/patches/v1/appeals.js';
export type {
  AccountDeletionStatus,
  AccountExport,
  AcknowledgePrivacyNoticeRequest,
  AcknowledgePrivacyNoticeResponse,
  CancelAccountDeletionRequest,
  CancelAccountDeletionResponse,
  ExportAccountRequest,
  ExportAccountResponse,
  GetDeletionStatusRequest,
  GetDeletionStatusResponse,
  GetExportStatusRequest,
  GetExportStatusResponse,
  GetPrivacyPrefsRequest,
  GetPrivacyPrefsResponse,
  PrivacyPrefs,
  PrivacyServiceClient,
  PrivacyServiceController,
  RequestAccountDeletionRequest,
  RequestAccountDeletionResponse,
  UpdatePrivacyPrefsRequest,
  UpdatePrivacyPrefsResponse,
} from './generated/patches/v1/privacy.js';
export type { AccountExportStatus } from './generated/patches/v1/privacy.js';

export {
  ACCOUNT_EXPORT_STATUS,
  APPEAL_STATUS,
  COMMUNITY_INVITE_STATUS,
  COMMUNITY_ROLE,
  CONVERSATION_KIND,
  CREDENTIAL_TYPE,
  DOMAIN_POLICY_ACTION,
  FEDERATION_STANCE,
  FILTER_ACTION,
  FILTER_SCOPE,
  FILTER_TERM_KIND,
  FILTERED_BY_PROVENANCE,
  FOLLOW_STATE,
  GITHUB_LOGIN_STATUS,
  LABEL_ACTION,
  MEDIA_STATUS,
  MESSAGE_REQUEST_STATUS,
  MODERATION_ACTION_TYPE,
  MODERATION_LOG_SUBJECT_KIND,
  MODERATION_REASON_CATEGORY,
  NOTIFICATION_TYPE,
  POST_TYPE,
  POST_VISIBILITY,
  QUOTE_POLICY,
  REGISTRATION_MODE,
  REPORT_REASON,
} from './enums.js';
export {
  createActorClient,
  createAppealClient,
  createAuthClient,
  createCommunityClient,
  createDirectMessageClient,
  createFeedClient,
  createFilterClient,
  createFilterListClient,
  createLabelClient,
  createMediaClient,
  createModerationClient,
  createNodeClient,
  createNotificationClient,
  createPageClient,
  createPostClient,
  createPrivacyClient,
  createReactionClient,
  createSocialGraphClient,
  createSystemClient,
  createTagClient,
} from './client.js';
export {
  DEADLINES_MS,
  ERROR_CODE_METADATA_KEY,
  GRPC_PACKAGES,
  METADATA_KEYS,
  MIN_CLIENT_VERSION,
  PATCHES_PACKAGE_NAME,
  PROTO_LOADER_OPTIONS,
  PROTOCOL_VERSION,
  SERVICE_NAMES,
} from './constants.js';
export type {
  ActorGrpcClient,
  AppealGrpcClient,
  AuthGrpcClient,
  CommunityGrpcClient,
  DirectMessageGrpcClient,
  FeedGrpcClient,
  FilterGrpcClient,
  FilterListGrpcClient,
  GrpcUnaryCall,
  LabelGrpcClient,
  MediaGrpcClient,
  ModerationGrpcClient,
  NodeGrpcClient,
  NotificationGrpcClient,
  PageGrpcClient,
  PostGrpcClient,
  PrivacyGrpcClient,
  ReactionGrpcClient,
  SocialGraphGrpcClient,
  SystemGrpcClient,
  TagGrpcClient,
} from './constants.js';
export { getProtoDir, getProtoFiles, protoFile } from './proto-path.js';
export { dateToTimestamp, timestampToDate } from './timestamps.js';
