/**
 * Nest-flavoured generated output: controller/client interfaces, the
 * `@XxxServiceControllerMethods()` class decorators, and enum values.
 *
 * Kept out of the package root on purpose — these modules import
 * `@nestjs/microservices` at runtime, and the ESM Ink TUI must never load Nest.
 * Only `apps/server` should import from `@patches/proto/nest`.
 *
 * Named re-exports rather than `export *` from every generated module: each generated file
 * declares its own `protobufPackage`/`PATCHES_V1_PACKAGE_NAME` constants (identical value,
 * same name), so a blanket `export *` from more than one of them is an ambiguous-export
 * compile error. `system.js`'s copy is exported once for both; the others are excluded here
 * on purpose, not missing.
 */
export * from './generated/patches/v1/system.js';

export type {
  Actor,
  ActorCounts,
  ActorFlair,
  ActorServiceClient,
  ActorServiceController,
  GetActorByHandleRequest,
  GetActorByHandleResponse,
  GetActorRequest,
  GetActorResponse,
  ListFollowersRequest,
  ListFollowersResponse,
  ListFollowingRequest,
  ListFollowingResponse,
  MediaRef,
  Nameplate,
  ResolveActorRequest,
  ResolveActorResponse,
  SearchActorsRequest,
  SearchActorsResponse,
  UpdateProfileRequest,
  UpdateProfileResponse,
} from './generated/patches/v1/actors.js';
export {
  ACTOR_SERVICE_NAME,
  ActorServiceControllerMethods,
} from './generated/patches/v1/actors.js';

export type {
  AddCredentialRequest,
  AddCredentialResponse,
  AuthServiceClient,
  AuthServiceController,
  BeginGitHubLoginRequest,
  BeginGitHubLoginResponse,
  BeginSshEnrollmentRequest,
  BeginSshEnrollmentResponse,
  BeginSshLoginRequest,
  BeginSshLoginResponse,
  CompleteSshLoginRequest,
  CompleteSshLoginResponse,
  Credential,
  GenerateRecoveryCodesRequest,
  GenerateRecoveryCodesResponse,
  GetAuthPolicyRequest,
  GetAuthPolicyResponse,
  GetCurrentSessionRequest,
  GetCurrentSessionResponse,
  ListCredentialsRequest,
  ListCredentialsResponse,
  LoginRequest,
  LoginResponse,
  LogoutAllSessionsRequest,
  LogoutAllSessionsResponse,
  LogoutRequest,
  LogoutResponse,
  PollGitHubLoginRequest,
  PollGitHubLoginResponse,
  RecoveryLoginRequest,
  RecoveryLoginResponse,
  RefreshSessionRequest,
  RefreshSessionResponse,
  RegisterRequest,
  RegisterResponse,
  RequestPasswordResetRequest,
  RequestPasswordResetResponse,
  ResendVerificationRequest,
  ResendVerificationResponse,
  ResetPasswordRequest,
  ResetPasswordResponse,
  RevokeCredentialRequest,
  RevokeCredentialResponse,
  Session,
  SshEnrollmentProof,
  VerifyEmailRequest,
  VerifyEmailResponse,
} from './generated/patches/v1/auth.js';
export {
  AUTH_SERVICE_NAME,
  AuthServiceControllerMethods,
  CredentialType,
  GitHubLoginStatus,
  PasswordAuthMode,
} from './generated/patches/v1/auth.js';

export type {
  CreatePostRequest,
  CreatePostResponse,
  DeletePostRequest,
  DeletePostResponse,
  EditPostRequest,
  EditPostResponse,
  FilteredByHint,
  GetPostRequest,
  GetPostResponse,
  ListPostEditsRequest,
  ListPostEditsResponse,
  ListRepliesRequest,
  ListRepliesResponse,
  MediaAttachment,
  PinPostRequest,
  PinPostResponse,
  Post,
  PostCounts,
  PostEdit,
  PostServiceClient,
  PostServiceController,
  PostViewerState,
  SearchPostsRequest,
  SearchPostsResponse,
  UnpinPostRequest,
  UnpinPostResponse,
} from './generated/patches/v1/posts.js';
export {
  FilteredByProvenance,
  POST_SERVICE_NAME,
  PostServiceControllerMethods,
  PostType,
  PostVisibility,
  QuotePolicy,
} from './generated/patches/v1/posts.js';

export type {
  FeedServiceClient,
  FeedServiceController,
  ListActorPostsRequest,
  ListActorPostsResponse,
  ListCommunityFeedRequest,
  ListCommunityFeedResponse,
  ListHomeFeedRequest,
  ListHomeFeedResponse,
  ListLocalFeedRequest,
  ListLocalFeedResponse,
  ListTagFeedRequest,
  ListTagFeedResponse,
} from './generated/patches/v1/feeds.js';
export { FEED_SERVICE_NAME, FeedServiceControllerMethods } from './generated/patches/v1/feeds.js';

export type {
  AcceptFollowRequestRequest,
  AcceptFollowRequestResponse,
  FollowActorRequest,
  FollowActorResponse,
  FollowRequest,
  GetRelationshipRequest,
  GetRelationshipResponse,
  ListFollowRequestsRequest,
  ListFollowRequestsResponse,
  ListMutualFollowsRequest,
  ListMutualFollowsResponse,
  RejectFollowRequestRequest,
  RejectFollowRequestResponse,
  Relationship,
  SocialGraphServiceClient,
  SocialGraphServiceController,
  UnfollowActorRequest,
  UnfollowActorResponse,
} from './generated/patches/v1/social_graph.js';
export {
  FollowState,
  SOCIAL_GRAPH_SERVICE_NAME,
  SocialGraphServiceControllerMethods,
} from './generated/patches/v1/social_graph.js';

export type {
  DomainPolicyEntry,
  GetNodeInfoRequest,
  GetNodeInfoResponse,
  GetNodePolicyRequest,
  GetNodePolicyResponse,
  NodeLimits,
  NodePolicy,
  NodeServiceClient,
  NodeServiceController,
  RetentionWindows,
  SocialCapabilities,
} from './generated/patches/v1/node.js';
export {
  DomainPolicyAction,
  FederationStance,
  NODE_SERVICE_NAME,
  NodeServiceControllerMethods,
  RegistrationMode,
} from './generated/patches/v1/node.js';

export type {
  BookmarkPostRequest,
  BookmarkPostResponse,
  ListBookmarksRequest,
  ListBookmarksResponse,
  ListPostLikersRequest,
  ListPostLikersResponse,
  ListPostRepostersRequest,
  ListPostRepostersResponse,
  LikePostRequest,
  LikePostResponse,
  ReactionServiceClient,
  ReactionServiceController,
  RepostPostRequest,
  RepostPostResponse,
  UnbookmarkPostRequest,
  UnbookmarkPostResponse,
  UnlikePostRequest,
  UnlikePostResponse,
  UnrepostPostRequest,
  UnrepostPostResponse,
} from './generated/patches/v1/reactions.js';
export {
  REACTION_SERVICE_NAME,
  ReactionServiceControllerMethods,
} from './generated/patches/v1/reactions.js';

export type {
  GetUnreadCountRequest,
  GetUnreadCountResponse,
  ListNotificationsRequest,
  ListNotificationsResponse,
  MarkNotificationsReadRequest,
  MarkNotificationsReadResponse,
  Notification,
  NotificationServiceClient,
  NotificationServiceController,
} from './generated/patches/v1/notifications.js';
export {
  NOTIFICATION_SERVICE_NAME,
  NotificationServiceControllerMethods,
  NotificationType,
} from './generated/patches/v1/notifications.js';

export type {
  BlockActorRequest,
  BlockActorResponse,
  ListBlocksRequest,
  ListBlocksResponse,
  ListModerationLogRequest,
  ListModerationLogResponse,
  ListMutesRequest,
  ListMutesResponse,
  ListMyModerationNoticesRequest,
  ListMyModerationNoticesResponse,
  ModerationLogEntry,
  ModerationNotice,
  ModerationServiceClient,
  ModerationServiceController,
  MuteActorRequest,
  MuteActorResponse,
  ReportActorRequest,
  ReportActorResponse,
  ReportMessageRequest,
  ReportMessageResponse,
  ReportPostRequest,
  ReportPostResponse,
  UnblockActorRequest,
  UnblockActorResponse,
  UnmuteActorRequest,
  UnmuteActorResponse,
} from './generated/patches/v1/moderation.js';
export {
  MODERATION_SERVICE_NAME,
  ModerationActionType,
  ModerationLogSubjectKind,
  ModerationReasonCategory,
  ModerationServiceControllerMethods,
  ReportReason,
} from './generated/patches/v1/moderation.js';

export type {
  BeginMediaUploadRequest,
  BeginMediaUploadResponse,
  FinalizeMediaUploadRequest,
  FinalizeMediaUploadResponse,
  GetMediaDownloadRequest,
  GetMediaDownloadResponse,
  MediaServiceClient,
  MediaServiceController,
} from './generated/patches/v1/media.js';
export {
  MEDIA_SERVICE_NAME,
  MediaServiceControllerMethods,
  MediaStatus,
} from './generated/patches/v1/media.js';

export type {
  GetPageRequest,
  GetPageResponse,
  GuestbookEntry,
  ListGuestbookRequest,
  ListGuestbookResponse,
  ListPageRevisionsRequest,
  ListPageRevisionsResponse,
  PageRevisionSummary,
  PageServiceClient,
  PageServiceController,
  PageTheme,
  RemoveGuestbookEntryRequest,
  RemoveGuestbookEntryResponse,
  ReportGuestbookEntryRequest,
  ReportGuestbookEntryResponse,
  SignGuestbookRequest,
  SignGuestbookResponse,
  UpdatePageRequest,
  UpdatePageResponse,
} from './generated/patches/v1/pages.js';
export { PAGE_SERVICE_NAME, PageServiceControllerMethods } from './generated/patches/v1/pages.js';

export type {
  BanFromCommunityRequest,
  BanFromCommunityResponse,
  Community,
  CommunityCounts,
  CommunityInvite,
  CommunityMember,
  CommunityServiceClient,
  CommunityServiceController,
  CreateCommunityRequest,
  CreateCommunityResponse,
  GetCommunityRequest,
  GetCommunityResponse,
  InviteToCommunityRequest,
  InviteToCommunityResponse,
  JoinCommunityRequest,
  JoinCommunityResponse,
  LeaveCommunityRequest,
  LeaveCommunityResponse,
  ListCommunitiesRequest,
  ListCommunitiesResponse,
  ListCommunityMembersRequest,
  ListCommunityMembersResponse,
  RemovePostFromCommunityRequest,
  RemovePostFromCommunityResponse,
  RespondToCommunityInviteRequest,
  RespondToCommunityInviteResponse,
  SetCommunityRoleRequest,
  SetCommunityRoleResponse,
  UpdateCommunityRequest,
  UpdateCommunityResponse,
} from './generated/patches/v1/communities.js';
export {
  COMMUNITY_SERVICE_NAME,
  CommunityInviteStatus,
  CommunityRole,
  CommunityServiceControllerMethods,
} from './generated/patches/v1/communities.js';

export type {
  Conversation,
  ConversationMember,
  CreateConversationRequest,
  CreateConversationResponse,
  DeleteMessageRequest,
  DeleteMessageResponse,
  DirectMessageServiceClient,
  DirectMessageServiceController,
  GetConversationRequest,
  GetConversationResponse,
  LeaveConversationRequest,
  LeaveConversationResponse,
  ListConversationsRequest,
  ListConversationsResponse,
  ListMessageRequestsRequest,
  ListMessageRequestsResponse,
  ListMessagesRequest,
  ListMessagesResponse,
  MarkConversationReadRequest,
  MarkConversationReadResponse,
  Message,
  MessageRequest,
  RespondToMessageRequestRequest,
  RespondToMessageRequestResponse,
  SendMessageRequest,
  SendMessageResponse,
} from './generated/patches/v1/messages.js';
export {
  ConversationKind,
  DIRECT_MESSAGE_SERVICE_NAME,
  DirectMessageServiceControllerMethods,
  MessageRequestStatus,
} from './generated/patches/v1/messages.js';

export type {
  AcknowledgeEnvelopesRequest,
  AcknowledgeEnvelopesResponse,
  AttachReportEvidenceRequest,
  AttachReportEvidenceResponse,
  ClaimPrekeyBundlesRequest,
  ClaimPrekeyBundlesResponse,
  CreateE2eeConversationRequest,
  CreateE2eeConversationResponse,
  E2eeCapability,
  E2eeConversationMemberState,
  E2eeDeviceCertificate,
  E2eeDeviceEnvelope,
  E2eeDeviceRoster,
  E2eeFrankingTag,
  E2eeIdentityRoot,
  E2eeLogicalMessage,
  E2eeMailboxEnvelope,
  E2eeOneTimePrekey,
  E2eePrekeyBundle,
  E2eeReportEvidenceItem,
  E2eeRosterEntry,
  E2eeServiceClient,
  E2eeServiceController,
  E2eeSignedPrekey,
  EnrollDeviceRequest,
  EnrollDeviceResponse,
  GetDeviceRosterRequest,
  GetDeviceRosterResponse,
  GetE2eeCapabilityRequest,
  GetE2eeCapabilityResponse,
  GetE2eeConversationStateRequest,
  GetE2eeConversationStateResponse,
  GetIdentityRootRequest,
  GetIdentityRootResponse,
  GetPrekeyInventoryRequest,
  GetPrekeyInventoryResponse,
  ListDeviceRostersRequest,
  ListDeviceRostersResponse,
  ListMailboxEnvelopesRequest,
  ListMailboxEnvelopesResponse,
  PublishDeviceRosterRequest,
  PublishDeviceRosterResponse,
  PublishIdentityRootRequest,
  PublishIdentityRootResponse,
  RevokeDeviceRequest,
  RevokeDeviceResponse,
  SendEnvelopesRequest,
  SendEnvelopesResponse,
  UploadPrekeysRequest,
  UploadPrekeysResponse,
} from './generated/patches/v1/e2ee.js';
export {
  ConversationSecurityMode,
  E2EE_SERVICE_NAME,
  E2eeCapabilityState,
  E2eeDeviceStatus,
  E2eeEvidenceVerificationStatus,
  E2eeServiceControllerMethods,
} from './generated/patches/v1/e2ee.js';

export type {
  ListMutedTagsRequest,
  ListMutedTagsResponse,
  MuteTagRequest,
  MuteTagResponse,
  SearchTagsRequest,
  SearchTagsResponse,
  Tag,
  TagServiceClient,
  TagServiceController,
  UnmuteTagRequest,
  UnmuteTagResponse,
} from './generated/patches/v1/tags.js';
export { TAG_SERVICE_NAME, TagServiceControllerMethods } from './generated/patches/v1/tags.js';

export type {
  CreateFilterRequest,
  CreateFilterResponse,
  DeleteFilterRequest,
  DeleteFilterResponse,
  ExportFiltersRequest,
  ExportFiltersResponse,
  Filter,
  FilterServiceClient,
  FilterServiceController,
  FilterTerm,
  FilterTermInput,
  ImportFiltersRequest,
  ImportFiltersResponse,
  ListFiltersRequest,
  ListFiltersResponse,
  UpdateFilterRequest,
  UpdateFilterResponse,
} from './generated/patches/v1/filters.js';
export {
  FILTER_SERVICE_NAME,
  FilterAction,
  FilterScope,
  FilterServiceControllerMethods,
  FilterTermKind,
} from './generated/patches/v1/filters.js';

export type {
  DeleteFilterListRequest,
  DeleteFilterListResponse,
  FilterList,
  FilterListEntry,
  FilterListServiceClient,
  FilterListServiceController,
  FilterListSubscription,
  GetFilterListRequest,
  GetFilterListResponse,
  ListFilterListEntriesRequest,
  ListFilterListEntriesResponse,
  ListFilterListsRequest,
  ListFilterListsResponse,
  ListFilterListSubscriptionsRequest,
  ListFilterListSubscriptionsResponse,
  PublishFilterListRequest,
  PublishFilterListResponse,
  SetFilterListEntryExceptionRequest,
  SetFilterListEntryExceptionResponse,
  SubscribeFilterListRequest,
  SubscribeFilterListResponse,
  UnsubscribeFilterListRequest,
  UnsubscribeFilterListResponse,
  UpdateFilterListRequest,
  UpdateFilterListResponse,
} from './generated/patches/v1/filter_lists.js';
export {
  FILTER_LIST_SERVICE_NAME,
  FilterListServiceControllerMethods,
} from './generated/patches/v1/filter_lists.js';

export type {
  ApplyLabelRequest,
  ApplyLabelResponse,
  CreateLabelerRequest,
  CreateLabelerResponse,
  GetLabelerRequest,
  GetLabelerResponse,
  Label,
  Labeler,
  LabelServiceClient,
  LabelServiceController,
  LabelVocabularyEntry,
  ListLabelersRequest,
  ListLabelersResponse,
  ListLabelsOnSubjectRequest,
  ListLabelsOnSubjectResponse,
  RetractLabelRequest,
  RetractLabelResponse,
  SetLabelerSubscriptionActionRequest,
  SetLabelerSubscriptionActionResponse,
  SubscribeLabelerRequest,
  SubscribeLabelerResponse,
  UnsubscribeLabelerRequest,
  UnsubscribeLabelerResponse,
} from './generated/patches/v1/labels.js';
export {
  LABEL_SERVICE_NAME,
  LabelAction,
  LabelServiceControllerMethods,
} from './generated/patches/v1/labels.js';

export type {
  Appeal,
  AppealServiceClient,
  AppealServiceController,
  CreateAppealRequest,
  CreateAppealResponse,
  GetAppealRequest,
  GetAppealResponse,
  ListMyAppealsRequest,
  ListMyAppealsResponse,
} from './generated/patches/v1/appeals.js';
export {
  APPEAL_SERVICE_NAME,
  AppealServiceControllerMethods,
  AppealStatus,
} from './generated/patches/v1/appeals.js';

export type {
  AccountDeletionStatus,
  AccountExport,
  AcknowledgePrivacyNoticeRequest,
  AcknowledgePrivacyNoticeResponse,
  CancelAccountDeletionRequest,
  CancelAccountDeletionResponse,
  ExportAccountRequest,
  ExportAccountResponse,
  GetDeletionStatusRequest,
  GetDeletionStatusResponse,
  GetExportStatusRequest,
  GetExportStatusResponse,
  GetPrivacyPrefsRequest,
  GetPrivacyPrefsResponse,
  PrivacyPrefs,
  PrivacyServiceClient,
  PrivacyServiceController,
  RequestAccountDeletionRequest,
  RequestAccountDeletionResponse,
  UpdatePrivacyPrefsRequest,
  UpdatePrivacyPrefsResponse,
} from './generated/patches/v1/privacy.js';
export {
  AccountExportStatus,
  PRIVACY_SERVICE_NAME,
  PrivacyServiceControllerMethods,
} from './generated/patches/v1/privacy.js';
