import { type Metadata } from '@grpc/grpc-js';
import { Controller, UseGuards } from '@nestjs/common';
import { Ctx, Payload } from '@nestjs/microservices';
import { dateToTimestamp } from '@patches/proto';
import {
  type AddCredentialRequest,
  type AddCredentialResponse,
  AuthServiceControllerMethods,
  type AuthServiceController,
  type BeginGitHubLoginRequest,
  type BeginGitHubLoginResponse,
  type BeginSshEnrollmentRequest,
  type BeginSshEnrollmentResponse,
  type BeginSshLoginRequest,
  type BeginSshLoginResponse,
  type CompleteSshLoginRequest,
  type CompleteSshLoginResponse,
  CredentialType,
  type GenerateRecoveryCodesRequest,
  type GenerateRecoveryCodesResponse,
  type GetAuthPolicyRequest,
  type GetAuthPolicyResponse,
  type GetCurrentSessionRequest,
  type GetCurrentSessionResponse,
  type ListCredentialsRequest,
  type ListCredentialsResponse,
  type LoginRequest,
  type LoginResponse,
  type LogoutAllSessionsRequest,
  type LogoutAllSessionsResponse,
  type LogoutRequest,
  type LogoutResponse,
  type PollGitHubLoginRequest,
  type PollGitHubLoginResponse,
  type RecoveryLoginRequest,
  type RecoveryLoginResponse,
  type RefreshSessionRequest,
  type RefreshSessionResponse,
  type RegisterRequest,
  type RegisterResponse,
  type RequestPasswordResetRequest,
  type RequestPasswordResetResponse,
  type ResendVerificationRequest,
  type ResendVerificationResponse,
  type ResetPasswordRequest,
  type ResetPasswordResponse,
  type RevokeCredentialRequest,
  type RevokeCredentialResponse,
  type VerifyEmailRequest,
  type VerifyEmailResponse,
} from '@patches/proto/nest';

import { AppError } from '../../common/errors/app-error.js';
import { AuthGuard, extractBearerToken } from './auth.guard.js';
import {
  credentialTypeFromProto,
  toProtoActor,
  toProtoCredential,
  toProtoGitHubLoginStatus,
  toProtoPasswordAuthMode,
  toProtoSession,
} from './auth.mapper.js';
import { AuthService } from './auth.service.js';
import { CurrentSession } from './session-context.js';
import { type AccessTokenClaims, TokenService } from './token.service.js';

/**
 * Transport adapter for `patches.v1.AuthService` — protobuf in, protobuf out, no business
 * logic (spec §128). Every method here does at most three things: turn a request message into
 * the service's own vocabulary, call the service, and map the result back.
 *
 * `@AuthServiceControllerMethods()` (generated by ts-proto) applies `@GrpcMethod` to every RPC
 * in `auth.proto`, so adding an RPC to the schema fails to compile here until it is handled.
 *
 * Protobuf scalars have no null: an unset `string` arrives as `''`. {@link blank} is the one
 * place that translates "empty" to "absent" so the service never has to think about it.
 */
@Controller()
@AuthServiceControllerMethods()
export class AuthController implements AuthServiceController {
  constructor(
    private readonly auth: AuthService,
    private readonly tokens: TokenService,
  ) {}

  getAuthPolicy(@Payload() _request: GetAuthPolicyRequest): GetAuthPolicyResponse {
    const policy = this.auth.getAuthPolicy();
    return { passwordAuth: toProtoPasswordAuthMode(policy.passwordAuthMode) };
  }

  async register(@Payload() request: RegisterRequest): Promise<RegisterResponse> {
    const session = await this.auth.register({
      handle: request.handle,
      displayName: request.displayName,
      ...optional('email', request.email),
      ...optional('password', request.password),
      ...optional('inviteCode', request.inviteCode),
      ...optional('sshPublicKey', request.sshPublicKey),
      ...optional('clientRequestId', request.clientRequestId),
      privacyNoticeVersionAcknowledged: request.privacyNoticeVersionAcknowledged,
    });
    return { session: toProtoSession(session) };
  }

  async verifyEmail(@Payload() request: VerifyEmailRequest): Promise<VerifyEmailResponse> {
    return { emailVerified: await this.auth.verifyEmail(request.code) };
  }

  @UseGuards(AuthGuard)
  async resendVerification(
    @Payload() _request: ResendVerificationRequest,
    @Ctx() _metadata?: Metadata,
    @CurrentSession() session?: AccessTokenClaims,
  ): Promise<ResendVerificationResponse> {
    await this.auth.resendVerification(requireSession(session));
    return {};
  }

  async login(@Payload() request: LoginRequest): Promise<LoginResponse> {
    const session = await this.auth.login({
      emailOrHandle: request.emailOrHandle,
      password: request.password,
    });
    return { session: toProtoSession(session) };
  }

  async recoveryLogin(@Payload() request: RecoveryLoginRequest): Promise<RecoveryLoginResponse> {
    const session = await this.auth.recoveryLogin({
      emailOrHandle: request.emailOrHandle,
      code: request.code,
    });
    return { session: toProtoSession(session) };
  }

  async refreshSession(@Payload() request: RefreshSessionRequest): Promise<RefreshSessionResponse> {
    const session = await this.auth.refreshSession(request.refreshToken);
    return { session: toProtoSession(session) };
  }

  async logout(@Payload() request: LogoutRequest): Promise<LogoutResponse> {
    await this.auth.logout(request.refreshToken);
    return {};
  }

  @UseGuards(AuthGuard)
  async logoutAllSessions(
    @Payload() _request: LogoutAllSessionsRequest,
    @Ctx() _metadata?: Metadata,
    @CurrentSession() session?: AccessTokenClaims,
  ): Promise<LogoutAllSessionsResponse> {
    await this.auth.logoutAllSessions(requireSession(session));
    return {};
  }

  async requestPasswordReset(
    @Payload() request: RequestPasswordResetRequest,
  ): Promise<RequestPasswordResetResponse> {
    await this.auth.requestPasswordReset(request.email);
    return {};
  }

  async resetPassword(@Payload() request: ResetPasswordRequest): Promise<ResetPasswordResponse> {
    await this.auth.resetPassword(request.code, request.newPassword);
    return {};
  }

  @UseGuards(AuthGuard)
  async getCurrentSession(
    @Payload() _request: GetCurrentSessionRequest,
    @Ctx() _metadata?: Metadata,
    @CurrentSession() session?: AccessTokenClaims,
  ): Promise<GetCurrentSessionResponse> {
    const current = await this.auth.getCurrentSession(requireSession(session));
    return {
      userId: current.userId,
      actor: toProtoActor(current.actor),
      sessionId: current.sessionId,
      expiresAt: dateToTimestamp(current.expiresAt),
      emailVerified: current.emailVerified,
      node: current.node,
    };
  }

  async beginSshLogin(@Payload() _request: BeginSshLoginRequest): Promise<BeginSshLoginResponse> {
    const challenge = await this.auth.beginSshLogin();
    return {
      challengeId: challenge.challengeId,
      nonce: challenge.nonce,
      expiresAt: dateToTimestamp(challenge.expiresAt),
    };
  }

  async completeSshLogin(
    @Payload() request: CompleteSshLoginRequest,
  ): Promise<CompleteSshLoginResponse> {
    const session = await this.auth.completeSshLogin({
      challengeId: request.challengeId,
      publicKeyOpenssh: request.publicKeyOpenssh,
      signature: Buffer.from(request.signature),
      signatureFormat: request.signatureFormat,
    });
    return { session: toProtoSession(session) };
  }

  @UseGuards(AuthGuard)
  async beginSshEnrollment(
    @Payload() request: BeginSshEnrollmentRequest,
    @Ctx() _metadata?: Metadata,
    @CurrentSession() session?: AccessTokenClaims,
  ): Promise<BeginSshEnrollmentResponse> {
    const challenge = await this.auth.beginSshEnrollment(
      requireSession(session),
      request.publicKeyOpenssh,
    );
    return {
      challengeId: challenge.challengeId,
      nonce: challenge.nonce,
      expiresAt: dateToTimestamp(challenge.expiresAt),
    };
  }

  /**
   * No `@UseGuards(AuthGuard)`: `BeginGitHubLogin` is valid both anonymously (login with an
   * already-linked GitHub credential) and authenticated (link GitHub to the caller's own
   * account, spec §167's "linking ... MUST require an authenticated Patches session" —
   * enforced by `AuthService` reading `callerUserId`, not by rejecting anonymous calls
   * outright, since the very same RPC also serves the login case). An invalid bearer token is
   * simply treated as anonymous rather than rejected — the guard's job is to reject bad
   * tokens on endpoints that *require* auth, not this one.
   */
  async beginGitHubLogin(
    @Payload() _request: BeginGitHubLoginRequest,
    @Ctx() metadata?: Metadata,
  ): Promise<BeginGitHubLoginResponse> {
    const callerUserId = await this.optionalCallerUserId(metadata);
    const begun = await this.auth.beginGitHubLogin(callerUserId);
    return {
      deviceCode: begun.deviceCode,
      userCode: begun.userCode,
      verificationUri: begun.verificationUri,
      interval: begun.interval,
      expiresAt: dateToTimestamp(begun.expiresAt),
    };
  }

  async pollGitHubLogin(
    @Payload() request: PollGitHubLoginRequest,
  ): Promise<PollGitHubLoginResponse> {
    const result = await this.auth.pollGitHubLogin(request.deviceCode);
    return {
      status: toProtoGitHubLoginStatus(result.status),
      session: result.status === 'COMPLETE' ? toProtoSession(result.session) : undefined,
    };
  }

  /** `undefined` for no token, an invalid token, or a token whose account is gone/suspended —
   * every one of those cases just means "treat this `BeginGitHubLogin` call as anonymous",
   * not "reject the call" (see the method's own doc comment above). */
  private async optionalCallerUserId(metadata: Metadata | undefined): Promise<string | undefined> {
    const token = extractBearerToken(metadata);
    if (token === undefined) return undefined;
    try {
      const claims = await this.tokens.verifyAccessToken(token);
      return claims.userId;
    } catch {
      return undefined;
    }
  }

  @UseGuards(AuthGuard)
  async listCredentials(
    @Payload() _request: ListCredentialsRequest,
    @Ctx() _metadata?: Metadata,
    @CurrentSession() session?: AccessTokenClaims,
  ): Promise<ListCredentialsResponse> {
    const credentials = await this.auth.listCredentials(requireSession(session));
    return { credentials: credentials.map(toProtoCredential) };
  }

  @UseGuards(AuthGuard)
  async addCredential(
    @Payload() request: AddCredentialRequest,
    @Ctx() _metadata?: Metadata,
    @CurrentSession() session?: AccessTokenClaims,
  ): Promise<AddCredentialResponse> {
    const type = credentialTypeFromProto(request.type);
    if (type === undefined || type === 'GITHUB') {
      throw AppError.validation(
        request.type === CredentialType.CREDENTIAL_TYPE_GITHUB
          ? 'Link a GitHub account through the GitHub login flow, not AddCredential.'
          : 'Specify a credential type of PASSWORD or SSH_PUBLIC_KEY.',
      );
    }

    const credential = await this.auth.addCredential(requireSession(session), {
      type,
      secret: request.secret,
      ...optional('label', request.label),
      // proto-loader decodes an unset embedded message as `null`, not `undefined` — ts-proto's
      // generated type only claims the latter, so both must be checked here.
      ...(request.sshProof === undefined || request.sshProof === null
        ? {}
        : {
            sshProof: {
              challengeId: request.sshProof.challengeId,
              signature: Buffer.from(request.sshProof.signature),
              signatureFormat: request.sshProof.signatureFormat,
            },
          }),
    });
    return { credential: toProtoCredential(credential) };
  }

  @UseGuards(AuthGuard)
  async revokeCredential(
    @Payload() request: RevokeCredentialRequest,
    @Ctx() _metadata?: Metadata,
    @CurrentSession() session?: AccessTokenClaims,
  ): Promise<RevokeCredentialResponse> {
    await this.auth.revokeCredential(requireSession(session), request.id);
    return {};
  }

  @UseGuards(AuthGuard)
  async generateRecoveryCodes(
    @Payload() _request: GenerateRecoveryCodesRequest,
    @Ctx() _metadata?: Metadata,
    @CurrentSession() session?: AccessTokenClaims,
  ): Promise<GenerateRecoveryCodesResponse> {
    const result = await this.auth.generateRecoveryCodes(requireSession(session));
    return { codes: [...result.codes], generatedAt: dateToTimestamp(result.generatedAt) };
  }
}

/** `''` is protobuf's only representation of an unset scalar; the service wants `undefined`. */
function blank(value: string): string | undefined {
  return value.length === 0 ? undefined : value;
}

/**
 * Builds `{ key: value }` or `{}`, so an unset protobuf scalar never becomes an explicit
 * `undefined` property — which `exactOptionalPropertyTypes` rightly treats as different from
 * an absent one.
 */
function optional<K extends string>(
  key: K,
  value: string,
): Record<K, string> | Record<never, never> {
  const trimmed = blank(value);
  return trimmed === undefined ? {} : { [key]: trimmed };
}

/**
 * The `@CurrentSession()` parameter is optional only because a ts-proto controller method
 * signature has no room for a required third parameter. `AuthGuard` has already run on every
 * method that uses it, so `undefined` here means the guard was forgotten — a programming
 * error, reported as an authentication failure rather than a crash.
 */
function requireSession(session: AccessTokenClaims | undefined): AccessTokenClaims {
  if (session === undefined) {
    throw new AppError('AUTH_INVALID_CREDENTIALS', 'Authentication required.');
  }
  return session;
}
