// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file patches/v1/appeals.proto (package patches.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv2';
import { enumDesc, fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';
import type { Timestamp } from '@bufbuild/protobuf/wkt';
import { file_google_protobuf_timestamp } from '@bufbuild/protobuf/wkt';
import type { PageInfo } from './common_pb.js';
import { file_patches_v1_common } from './common_pb.js';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file patches/v1/appeals.proto.
 */
export const file_patches_v1_appeals: GenFile =
  /*@__PURE__*/
  fileDesc(
    'ChhwYXRjaGVzL3YxL2FwcGVhbHMucHJvdG8SCnBhdGNoZXMudjEi6wEKBkFwcGVhbBIKCgJpZBgBIAEoCRIcChRtb2RlcmF0aW9uX25vdGljZV9pZBgCIAEoCRIRCglzdGF0ZW1lbnQYAyABKAkSKAoGc3RhdHVzGAQgASgOMhgucGF0Y2hlcy52MS5BcHBlYWxTdGF0dXMSLgoKY3JlYXRlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLwoLcmVzb2x2ZWRfYXQYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhkKEXJlc29sdXRpb25fcmVhc29uGAcgASgJIkYKE0NyZWF0ZUFwcGVhbFJlcXVlc3QSHAoUbW9kZXJhdGlvbl9ub3RpY2VfaWQYASABKAkSEQoJc3RhdGVtZW50GAIgASgJIjoKFENyZWF0ZUFwcGVhbFJlc3BvbnNlEiIKBmFwcGVhbBgBIAEoCzISLnBhdGNoZXMudjEuQXBwZWFsIh4KEEdldEFwcGVhbFJlcXVlc3QSCgoCaWQYASABKAkiNwoRR2V0QXBwZWFsUmVzcG9uc2USIgoGYXBwZWFsGAEgASgLMhIucGF0Y2hlcy52MS5BcHBlYWwiNQoUTGlzdE15QXBwZWFsc1JlcXVlc3QSDgoGY3Vyc29yGAEgASgJEg0KBWxpbWl0GAIgASgNImAKFUxpc3RNeUFwcGVhbHNSZXNwb25zZRIjCgdhcHBlYWxzGAEgAygLMhIucGF0Y2hlcy52MS5BcHBlYWwSIgoEcGFnZRgCIAEoCzIULnBhdGNoZXMudjEuUGFnZUluZm8qmQEKDEFwcGVhbFN0YXR1cxIdChlBUFBFQUxfU1RBVFVTX1VOU1BFQ0lGSUVEEAASFgoSQVBQRUFMX1NUQVRVU19PUEVOEAESGAoUQVBQRUFMX1NUQVRVU19VUEhFTEQQAhIcChhBUFBFQUxfU1RBVFVTX09WRVJUVVJORUQQAxIaChZBUFBFQUxfU1RBVFVTX01PRElGSUVEEAQyggIKDUFwcGVhbFNlcnZpY2USUQoMQ3JlYXRlQXBwZWFsEh8ucGF0Y2hlcy52MS5DcmVhdGVBcHBlYWxSZXF1ZXN0GiAucGF0Y2hlcy52MS5DcmVhdGVBcHBlYWxSZXNwb25zZRJICglHZXRBcHBlYWwSHC5wYXRjaGVzLnYxLkdldEFwcGVhbFJlcXVlc3QaHS5wYXRjaGVzLnYxLkdldEFwcGVhbFJlc3BvbnNlElQKDUxpc3RNeUFwcGVhbHMSIC5wYXRjaGVzLnYxLkxpc3RNeUFwcGVhbHNSZXF1ZXN0GiEucGF0Y2hlcy52MS5MaXN0TXlBcHBlYWxzUmVzcG9uc2ViBnByb3RvMw',
    [file_google_protobuf_timestamp, file_patches_v1_common],
  );

/**
 * Visible only to the appellant and moderators (§201.3, §208) — the public moderation log
 * shows only that an action was appealed (a boolean), never this message's content.
 *
 * @generated from message patches.v1.Appeal
 */
export type Appeal = Message<'patches.v1.Appeal'> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string moderation_notice_id = 2;
   */
  moderationNoticeId: string;

  /**
   * Max 2,000 characters (spec §204).
   *
   * @generated from field: string statement = 3;
   */
  statement: string;

  /**
   * @generated from field: patches.v1.AppealStatus status = 4;
   */
  status: AppealStatus;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp | undefined;

  /**
   * Unset until resolved.
   *
   * @generated from field: google.protobuf.Timestamp resolved_at = 6;
   */
  resolvedAt?: Timestamp | undefined;

  /**
   * Authored by the resolving moderator — never `reports.moderator_note` or any other
   * internal-only field (spec §55, §201.3, §208).
   *
   * @generated from field: string resolution_reason = 7;
   */
  resolutionReason: string;
};

/**
 * Describes the message patches.v1.Appeal.
 * Use `create(AppealSchema)` to create a new message.
 */
export const AppealSchema: GenMessage<Appeal> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_appeals, 0);

/**
 * @generated from message patches.v1.CreateAppealRequest
 */
export type CreateAppealRequest = Message<'patches.v1.CreateAppealRequest'> & {
  /**
   * @generated from field: string moderation_notice_id = 1;
   */
  moderationNoticeId: string;

  /**
   * @generated from field: string statement = 2;
   */
  statement: string;
};

/**
 * Describes the message patches.v1.CreateAppealRequest.
 * Use `create(CreateAppealRequestSchema)` to create a new message.
 */
export const CreateAppealRequestSchema: GenMessage<CreateAppealRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_appeals, 1);

/**
 * @generated from message patches.v1.CreateAppealResponse
 */
export type CreateAppealResponse = Message<'patches.v1.CreateAppealResponse'> & {
  /**
   * @generated from field: patches.v1.Appeal appeal = 1;
   */
  appeal?: Appeal | undefined;
};

/**
 * Describes the message patches.v1.CreateAppealResponse.
 * Use `create(CreateAppealResponseSchema)` to create a new message.
 */
export const CreateAppealResponseSchema: GenMessage<CreateAppealResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_appeals, 2);

/**
 * @generated from message patches.v1.GetAppealRequest
 */
export type GetAppealRequest = Message<'patches.v1.GetAppealRequest'> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message patches.v1.GetAppealRequest.
 * Use `create(GetAppealRequestSchema)` to create a new message.
 */
export const GetAppealRequestSchema: GenMessage<GetAppealRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_appeals, 3);

/**
 * @generated from message patches.v1.GetAppealResponse
 */
export type GetAppealResponse = Message<'patches.v1.GetAppealResponse'> & {
  /**
   * @generated from field: patches.v1.Appeal appeal = 1;
   */
  appeal?: Appeal | undefined;
};

/**
 * Describes the message patches.v1.GetAppealResponse.
 * Use `create(GetAppealResponseSchema)` to create a new message.
 */
export const GetAppealResponseSchema: GenMessage<GetAppealResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_appeals, 4);

/**
 * @generated from message patches.v1.ListMyAppealsRequest
 */
export type ListMyAppealsRequest = Message<'patches.v1.ListMyAppealsRequest'> & {
  /**
   * @generated from field: string cursor = 1;
   */
  cursor: string;

  /**
   * @generated from field: uint32 limit = 2;
   */
  limit: number;
};

/**
 * Describes the message patches.v1.ListMyAppealsRequest.
 * Use `create(ListMyAppealsRequestSchema)` to create a new message.
 */
export const ListMyAppealsRequestSchema: GenMessage<ListMyAppealsRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_appeals, 5);

/**
 * @generated from message patches.v1.ListMyAppealsResponse
 */
export type ListMyAppealsResponse = Message<'patches.v1.ListMyAppealsResponse'> & {
  /**
   * @generated from field: repeated patches.v1.Appeal appeals = 1;
   */
  appeals: Appeal[];

  /**
   * @generated from field: patches.v1.PageInfo page = 2;
   */
  page?: PageInfo | undefined;
};

/**
 * Describes the message patches.v1.ListMyAppealsResponse.
 * Use `create(ListMyAppealsResponseSchema)` to create a new message.
 */
export const ListMyAppealsResponseSchema: GenMessage<ListMyAppealsResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_appeals, 6);

/**
 * @generated from enum patches.v1.AppealStatus
 */
export enum AppealStatus {
  /**
   * @generated from enum value: APPEAL_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: APPEAL_STATUS_OPEN = 1;
   */
  OPEN = 1,

  /**
   * @generated from enum value: APPEAL_STATUS_UPHELD = 2;
   */
  UPHELD = 2,

  /**
   * @generated from enum value: APPEAL_STATUS_OVERTURNED = 3;
   */
  OVERTURNED = 3,

  /**
   * @generated from enum value: APPEAL_STATUS_MODIFIED = 4;
   */
  MODIFIED = 4,
}

/**
 * Describes the enum patches.v1.AppealStatus.
 */
export const AppealStatusSchema: GenEnum<AppealStatus> =
  /*@__PURE__*/
  enumDesc(file_patches_v1_appeals, 0);

/**
 * Appeals against a node moderation notice (spec §201.3). Only the acted-upon actor may
 * appeal — not a reporter, not a bystander. One appeal per moderation notice. Admin-side
 * resolution is CLI-only (`patches-admin appeal list|inspect|resolve`) — there is
 * deliberately no gRPC resolve RPC here, mirroring `report list|inspect|resolve`.
 *
 * @generated from service patches.v1.AppealService
 */
export const AppealService: GenService<{
  /**
   * `moderation_notice_id` identifies the notice being appealed
   * (`ModerationService.ListMyModerationNotices`). Rejected if the caller already has an
   * appeal for that notice, or the node's published appeal window has closed
   * (`NodeService.GetNodePolicy`).
   *
   * @generated from rpc patches.v1.AppealService.CreateAppeal
   */
  createAppeal: {
    methodKind: 'unary';
    input: typeof CreateAppealRequestSchema;
    output: typeof CreateAppealResponseSchema;
  };
  /**
   * @generated from rpc patches.v1.AppealService.GetAppeal
   */
  getAppeal: {
    methodKind: 'unary';
    input: typeof GetAppealRequestSchema;
    output: typeof GetAppealResponseSchema;
  };
  /**
   * The caller's own appeals, most-recent first.
   *
   * @generated from rpc patches.v1.AppealService.ListMyAppeals
   */
  listMyAppeals: {
    methodKind: 'unary';
    input: typeof ListMyAppealsRequestSchema;
    output: typeof ListMyAppealsResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_patches_v1_appeals, 0);
