// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file patches/v1/feeds.proto (package patches.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';
import type { PageInfo } from './common_pb.js';
import { file_patches_v1_common } from './common_pb.js';
import type { Post } from './posts_pb.js';
import { file_patches_v1_posts } from './posts_pb.js';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file patches/v1/feeds.proto.
 */
export const file_patches_v1_feeds: GenFile =
  /*@__PURE__*/
  fileDesc(
    'ChZwYXRjaGVzL3YxL2ZlZWRzLnByb3RvEgpwYXRjaGVzLnYxIjQKE0xpc3RIb21lRmVlZFJlcXVlc3QSDgoGY3Vyc29yGAEgASgJEg0KBWxpbWl0GAIgASgNIlsKFExpc3RIb21lRmVlZFJlc3BvbnNlEh8KBXBvc3RzGAEgAygLMhAucGF0Y2hlcy52MS5Qb3N0EiIKBHBhZ2UYAiABKAsyFC5wYXRjaGVzLnYxLlBhZ2VJbmZvIjUKFExpc3RMb2NhbEZlZWRSZXF1ZXN0Eg4KBmN1cnNvchgBIAEoCRINCgVsaW1pdBgCIAEoDSJcChVMaXN0TG9jYWxGZWVkUmVzcG9uc2USHwoFcG9zdHMYASADKAsyEC5wYXRjaGVzLnYxLlBvc3QSIgoEcGFnZRgCIAEoCzIULnBhdGNoZXMudjEuUGFnZUluZm8iSAoVTGlzdEFjdG9yUG9zdHNSZXF1ZXN0EhAKCGFjdG9yX2lkGAEgASgJEg4KBmN1cnNvchgCIAEoCRINCgVsaW1pdBgDIAEoDSJdChZMaXN0QWN0b3JQb3N0c1Jlc3BvbnNlEh8KBXBvc3RzGAEgAygLMhAucGF0Y2hlcy52MS5Qb3N0EiIKBHBhZ2UYAiABKAsyFC5wYXRjaGVzLnYxLlBhZ2VJbmZvIkAKEkxpc3RUYWdGZWVkUmVxdWVzdBILCgN0YWcYASABKAkSDgoGY3Vyc29yGAIgASgJEg0KBWxpbWl0GAMgASgNIloKE0xpc3RUYWdGZWVkUmVzcG9uc2USHwoFcG9zdHMYASADKAsyEC5wYXRjaGVzLnYxLlBvc3QSIgoEcGFnZRgCIAEoCzIULnBhdGNoZXMudjEuUGFnZUluZm8iTwoYTGlzdENvbW11bml0eUZlZWRSZXF1ZXN0EhQKDGNvbW11bml0eV9pZBgBIAEoCRIOCgZjdXJzb3IYAiABKAkSDQoFbGltaXQYAyABKA0iYAoZTGlzdENvbW11bml0eUZlZWRSZXNwb25zZRIfCgVwb3N0cxgBIAMoCzIQLnBhdGNoZXMudjEuUG9zdBIiCgRwYWdlGAIgASgLMhQucGF0Y2hlcy52MS5QYWdlSW5mbzLBAwoLRmVlZFNlcnZpY2USUQoMTGlzdEhvbWVGZWVkEh8ucGF0Y2hlcy52MS5MaXN0SG9tZUZlZWRSZXF1ZXN0GiAucGF0Y2hlcy52MS5MaXN0SG9tZUZlZWRSZXNwb25zZRJUCg1MaXN0TG9jYWxGZWVkEiAucGF0Y2hlcy52MS5MaXN0TG9jYWxGZWVkUmVxdWVzdBohLnBhdGNoZXMudjEuTGlzdExvY2FsRmVlZFJlc3BvbnNlElcKDkxpc3RBY3RvclBvc3RzEiEucGF0Y2hlcy52MS5MaXN0QWN0b3JQb3N0c1JlcXVlc3QaIi5wYXRjaGVzLnYxLkxpc3RBY3RvclBvc3RzUmVzcG9uc2USTgoLTGlzdFRhZ0ZlZWQSHi5wYXRjaGVzLnYxLkxpc3RUYWdGZWVkUmVxdWVzdBofLnBhdGNoZXMudjEuTGlzdFRhZ0ZlZWRSZXNwb25zZRJgChFMaXN0Q29tbXVuaXR5RmVlZBIkLnBhdGNoZXMudjEuTGlzdENvbW11bml0eUZlZWRSZXF1ZXN0GiUucGF0Y2hlcy52MS5MaXN0Q29tbXVuaXR5RmVlZFJlc3BvbnNlYgZwcm90bzM',
    [file_patches_v1_common, file_patches_v1_posts],
  );

/**
 * @generated from message patches.v1.ListHomeFeedRequest
 */
export type ListHomeFeedRequest = Message<'patches.v1.ListHomeFeedRequest'> & {
  /**
   * @generated from field: string cursor = 1;
   */
  cursor: string;

  /**
   * @generated from field: uint32 limit = 2;
   */
  limit: number;
};

/**
 * Describes the message patches.v1.ListHomeFeedRequest.
 * Use `create(ListHomeFeedRequestSchema)` to create a new message.
 */
export const ListHomeFeedRequestSchema: GenMessage<ListHomeFeedRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_feeds, 0);

/**
 * @generated from message patches.v1.ListHomeFeedResponse
 */
export type ListHomeFeedResponse = Message<'patches.v1.ListHomeFeedResponse'> & {
  /**
   * @generated from field: repeated patches.v1.Post posts = 1;
   */
  posts: Post[];

  /**
   * @generated from field: patches.v1.PageInfo page = 2;
   */
  page?: PageInfo | undefined;
};

/**
 * Describes the message patches.v1.ListHomeFeedResponse.
 * Use `create(ListHomeFeedResponseSchema)` to create a new message.
 */
export const ListHomeFeedResponseSchema: GenMessage<ListHomeFeedResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_feeds, 1);

/**
 * @generated from message patches.v1.ListLocalFeedRequest
 */
export type ListLocalFeedRequest = Message<'patches.v1.ListLocalFeedRequest'> & {
  /**
   * @generated from field: string cursor = 1;
   */
  cursor: string;

  /**
   * @generated from field: uint32 limit = 2;
   */
  limit: number;
};

/**
 * Describes the message patches.v1.ListLocalFeedRequest.
 * Use `create(ListLocalFeedRequestSchema)` to create a new message.
 */
export const ListLocalFeedRequestSchema: GenMessage<ListLocalFeedRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_feeds, 2);

/**
 * @generated from message patches.v1.ListLocalFeedResponse
 */
export type ListLocalFeedResponse = Message<'patches.v1.ListLocalFeedResponse'> & {
  /**
   * @generated from field: repeated patches.v1.Post posts = 1;
   */
  posts: Post[];

  /**
   * @generated from field: patches.v1.PageInfo page = 2;
   */
  page?: PageInfo | undefined;
};

/**
 * Describes the message patches.v1.ListLocalFeedResponse.
 * Use `create(ListLocalFeedResponseSchema)` to create a new message.
 */
export const ListLocalFeedResponseSchema: GenMessage<ListLocalFeedResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_feeds, 3);

/**
 * @generated from message patches.v1.ListActorPostsRequest
 */
export type ListActorPostsRequest = Message<'patches.v1.ListActorPostsRequest'> & {
  /**
   * @generated from field: string actor_id = 1;
   */
  actorId: string;

  /**
   * @generated from field: string cursor = 2;
   */
  cursor: string;

  /**
   * @generated from field: uint32 limit = 3;
   */
  limit: number;
};

/**
 * Describes the message patches.v1.ListActorPostsRequest.
 * Use `create(ListActorPostsRequestSchema)` to create a new message.
 */
export const ListActorPostsRequestSchema: GenMessage<ListActorPostsRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_feeds, 4);

/**
 * @generated from message patches.v1.ListActorPostsResponse
 */
export type ListActorPostsResponse = Message<'patches.v1.ListActorPostsResponse'> & {
  /**
   * @generated from field: repeated patches.v1.Post posts = 1;
   */
  posts: Post[];

  /**
   * @generated from field: patches.v1.PageInfo page = 2;
   */
  page?: PageInfo | undefined;
};

/**
 * Describes the message patches.v1.ListActorPostsResponse.
 * Use `create(ListActorPostsResponseSchema)` to create a new message.
 */
export const ListActorPostsResponseSchema: GenMessage<ListActorPostsResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_feeds, 5);

/**
 * @generated from message patches.v1.ListTagFeedRequest
 */
export type ListTagFeedRequest = Message<'patches.v1.ListTagFeedRequest'> & {
  /**
   * Tag name — matched against the canonical (NFKC-normalized, casefolded) form.
   *
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * @generated from field: string cursor = 2;
   */
  cursor: string;

  /**
   * @generated from field: uint32 limit = 3;
   */
  limit: number;
};

/**
 * Describes the message patches.v1.ListTagFeedRequest.
 * Use `create(ListTagFeedRequestSchema)` to create a new message.
 */
export const ListTagFeedRequestSchema: GenMessage<ListTagFeedRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_feeds, 6);

/**
 * @generated from message patches.v1.ListTagFeedResponse
 */
export type ListTagFeedResponse = Message<'patches.v1.ListTagFeedResponse'> & {
  /**
   * @generated from field: repeated patches.v1.Post posts = 1;
   */
  posts: Post[];

  /**
   * @generated from field: patches.v1.PageInfo page = 2;
   */
  page?: PageInfo | undefined;
};

/**
 * Describes the message patches.v1.ListTagFeedResponse.
 * Use `create(ListTagFeedResponseSchema)` to create a new message.
 */
export const ListTagFeedResponseSchema: GenMessage<ListTagFeedResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_feeds, 7);

/**
 * @generated from message patches.v1.ListCommunityFeedRequest
 */
export type ListCommunityFeedRequest = Message<'patches.v1.ListCommunityFeedRequest'> & {
  /**
   * @generated from field: string community_id = 1;
   */
  communityId: string;

  /**
   * @generated from field: string cursor = 2;
   */
  cursor: string;

  /**
   * @generated from field: uint32 limit = 3;
   */
  limit: number;
};

/**
 * Describes the message patches.v1.ListCommunityFeedRequest.
 * Use `create(ListCommunityFeedRequestSchema)` to create a new message.
 */
export const ListCommunityFeedRequestSchema: GenMessage<ListCommunityFeedRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_feeds, 8);

/**
 * @generated from message patches.v1.ListCommunityFeedResponse
 */
export type ListCommunityFeedResponse = Message<'patches.v1.ListCommunityFeedResponse'> & {
  /**
   * @generated from field: repeated patches.v1.Post posts = 1;
   */
  posts: Post[];

  /**
   * @generated from field: patches.v1.PageInfo page = 2;
   */
  page?: PageInfo | undefined;
};

/**
 * Describes the message patches.v1.ListCommunityFeedResponse.
 * Use `create(ListCommunityFeedResponseSchema)` to create a new message.
 */
export const ListCommunityFeedResponseSchema: GenMessage<ListCommunityFeedResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_feeds, 9);

/**
 * Chronological, fan-out-on-read feeds (spec §52, §59). Never `GetRecommendedFeed`/
 * `GetForYouFeed` — there is no engagement-ranked feed in this product (spec §153).
 *
 * @generated from service patches.v1.FeedService
 */
export const FeedService: GenService<{
  /**
   * The caller's home timeline: local + followed actors, fan-out-on-read, chronological.
   *
   * @generated from rpc patches.v1.FeedService.ListHomeFeed
   */
  listHomeFeed: {
    methodKind: 'unary';
    input: typeof ListHomeFeedRequestSchema;
    output: typeof ListHomeFeedResponseSchema;
  };
  /**
   * All local public posts, chronological.
   *
   * @generated from rpc patches.v1.FeedService.ListLocalFeed
   */
  listLocalFeed: {
    methodKind: 'unary';
    input: typeof ListLocalFeedRequestSchema;
    output: typeof ListLocalFeedResponseSchema;
  };
  /**
   * A given actor's posts, chronological.
   *
   * @generated from rpc patches.v1.FeedService.ListActorPosts
   */
  listActorPosts: {
    methodKind: 'unary';
    input: typeof ListActorPostsRequestSchema;
    output: typeof ListActorPostsResponseSchema;
  };
  /**
   * All public posts carrying a given tag, chronological. No ordering parameter — same
   * chronological-only rule as every other feed (spec §182.2).
   *
   * @generated from rpc patches.v1.FeedService.ListTagFeed
   */
  listTagFeed: {
    methodKind: 'unary';
    input: typeof ListTagFeedRequestSchema;
    output: typeof ListTagFeedResponseSchema;
  };
  /**
   * A community's posts, chronological. No ordering parameter (spec §182.2).
   *
   * @generated from rpc patches.v1.FeedService.ListCommunityFeed
   */
  listCommunityFeed: {
    methodKind: 'unary';
    input: typeof ListCommunityFeedRequestSchema;
    output: typeof ListCommunityFeedResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_patches_v1_feeds, 0);
