// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file patches/v1/node.proto (package patches.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv2';
import { enumDesc, fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file patches/v1/node.proto.
 */
export const file_patches_v1_node: GenFile =
  /*@__PURE__*/
  fileDesc(
    'ChVwYXRjaGVzL3YxL25vZGUucHJvdG8SCnBhdGNoZXMudjEi9gEKCk5vZGVMaW1pdHMSGwoTcG9zdF9ib2R5X21heF9jaGFycxgBIAEoDRIVCg1iaW9fbWF4X2NoYXJzGAIgASgNEh4KFmRpc3BsYXlfbmFtZV9tYXhfY2hhcnMYAyABKA0SGAoQaGFuZGxlX21heF9jaGFycxgEIAEoDRIfChdsb2NhdGlvbl90ZXh0X21heF9jaGFycxgFIAEoDRIdChV3ZWJzaXRlX3VybF9tYXhfY2hhcnMYBiABKA0SGgoSYWx0X3RleHRfbWF4X2NoYXJzGAcgASgNEh4KFnNlYXJjaF9xdWVyeV9tYXhfY2hhcnMYCCABKA0iFAoSR2V0Tm9kZUluZm9SZXF1ZXN0IrYBChNHZXROb2RlSW5mb1Jlc3BvbnNlEg4KBmRvbWFpbhgBIAEoCRIYChBzb2Z0d2FyZV92ZXJzaW9uGAIgASgJEjcKEXJlZ2lzdHJhdGlvbl9tb2RlGAMgASgOMhwucGF0Y2hlcy52MS5SZWdpc3RyYXRpb25Nb2RlEiYKBmxpbWl0cxgEIAEoCzIWLnBhdGNoZXMudjEuTm9kZUxpbWl0cxIUCgxjYXBhYmlsaXRpZXMYBSADKAkqdAoQUmVnaXN0cmF0aW9uTW9kZRIhCh1SRUdJU1RSQVRJT05fTU9ERV9VTlNQRUNJRklFRBAAEhoKFlJFR0lTVFJBVElPTl9NT0RFX09QRU4QARIhCh1SRUdJU1RSQVRJT05fTU9ERV9JTlZJVEVfT05MWRACMl0KC05vZGVTZXJ2aWNlEk4KC0dldE5vZGVJbmZvEh4ucGF0Y2hlcy52MS5HZXROb2RlSW5mb1JlcXVlc3QaHy5wYXRjaGVzLnYxLkdldE5vZGVJbmZvUmVzcG9uc2ViBnByb3RvMw',
  );

/**
 * Input limits this node enforces (spec §58) — clients validate/render against these rather
 * than hardcoding the reference node's numbers.
 *
 * @generated from message patches.v1.NodeLimits
 */
export type NodeLimits = Message<'patches.v1.NodeLimits'> & {
  /**
   * @generated from field: uint32 post_body_max_chars = 1;
   */
  postBodyMaxChars: number;

  /**
   * @generated from field: uint32 bio_max_chars = 2;
   */
  bioMaxChars: number;

  /**
   * @generated from field: uint32 display_name_max_chars = 3;
   */
  displayNameMaxChars: number;

  /**
   * @generated from field: uint32 handle_max_chars = 4;
   */
  handleMaxChars: number;

  /**
   * @generated from field: uint32 location_text_max_chars = 5;
   */
  locationTextMaxChars: number;

  /**
   * @generated from field: uint32 website_url_max_chars = 6;
   */
  websiteUrlMaxChars: number;

  /**
   * @generated from field: uint32 alt_text_max_chars = 7;
   */
  altTextMaxChars: number;

  /**
   * @generated from field: uint32 search_query_max_chars = 8;
   */
  searchQueryMaxChars: number;
};

/**
 * Describes the message patches.v1.NodeLimits.
 * Use `create(NodeLimitsSchema)` to create a new message.
 */
export const NodeLimitsSchema: GenMessage<NodeLimits> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_node, 0);

/**
 * @generated from message patches.v1.GetNodeInfoRequest
 */
export type GetNodeInfoRequest = Message<'patches.v1.GetNodeInfoRequest'> & {};

/**
 * Describes the message patches.v1.GetNodeInfoRequest.
 * Use `create(GetNodeInfoRequestSchema)` to create a new message.
 */
export const GetNodeInfoRequestSchema: GenMessage<GetNodeInfoRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_node, 1);

/**
 * @generated from message patches.v1.GetNodeInfoResponse
 */
export type GetNodeInfoResponse = Message<'patches.v1.GetNodeInfoResponse'> & {
  /**
   * Canonical domain of this node (spec §91, §163). Empty until a domain is fixed.
   *
   * @generated from field: string domain = 1;
   */
  domain: string;

  /**
   * Node software version (semver) — distinct from `SystemService.GetServerInfo`'s
   * `protocol_version`/`min_client_version`, which describe the wire protocol, not the
   * software build.
   *
   * @generated from field: string software_version = 2;
   */
  softwareVersion: string;

  /**
   * @generated from field: patches.v1.RegistrationMode registration_mode = 3;
   */
  registrationMode: RegistrationMode;

  /**
   * @generated from field: patches.v1.NodeLimits limits = 4;
   */
  limits?: NodeLimits | undefined;

  /**
   * Capabilities this node grants (spec §174). There is deliberately no `tier`/`plan`/
   * `premium` field anywhere in this message, and there never will be — clients branch on
   * capabilities only. Clients must tolerate unknown entries.
   *
   * @generated from field: repeated string capabilities = 5;
   */
  capabilities: string[];
};

/**
 * Describes the message patches.v1.GetNodeInfoResponse.
 * Use `create(GetNodeInfoResponseSchema)` to create a new message.
 */
export const GetNodeInfoResponseSchema: GenMessage<GetNodeInfoResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_node, 2);

/**
 * @generated from enum patches.v1.RegistrationMode
 */
export enum RegistrationMode {
  /**
   * @generated from enum value: REGISTRATION_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: REGISTRATION_MODE_OPEN = 1;
   */
  OPEN = 1,

  /**
   * @generated from enum value: REGISTRATION_MODE_INVITE_ONLY = 2;
   */
  INVITE_ONLY = 2,
}

/**
 * Describes the enum patches.v1.RegistrationMode.
 */
export const RegistrationModeSchema: GenEnum<RegistrationMode> =
  /*@__PURE__*/
  enumDesc(file_patches_v1_node, 0);

/**
 * Node discovery (spec §163, §168, §174) — always unauthenticated. A client calls
 * `GetNodeInfo` before assuming any policy (registration mode, limits, capabilities) rather
 * than hardcoding the reference node's behavior.
 *
 * @generated from service patches.v1.NodeService
 */
export const NodeService: GenService<{
  /**
   * @generated from rpc patches.v1.NodeService.GetNodeInfo
   */
  getNodeInfo: {
    methodKind: 'unary';
    input: typeof GetNodeInfoRequestSchema;
    output: typeof GetNodeInfoResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_patches_v1_node, 0);
