// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file patches/v1/notifications.proto (package patches.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv2';
import { enumDesc, fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';
import type { Timestamp } from '@bufbuild/protobuf/wkt';
import { file_google_protobuf_timestamp } from '@bufbuild/protobuf/wkt';
import type { Actor } from './actors_pb.js';
import { file_patches_v1_actors } from './actors_pb.js';
import type { PageInfo } from './common_pb.js';
import { file_patches_v1_common } from './common_pb.js';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file patches/v1/notifications.proto.
 */
export const file_patches_v1_notifications: GenFile =
  /*@__PURE__*/
  fileDesc(
    'Ch5wYXRjaGVzL3YxL25vdGlmaWNhdGlvbnMucHJvdG8SCnBhdGNoZXMudjEihQIKDE5vdGlmaWNhdGlvbhIKCgJpZBgBIAEoCRIqCgR0eXBlGAIgASgOMhwucGF0Y2hlcy52MS5Ob3RpZmljYXRpb25UeXBlEiAKBWFjdG9yGAMgASgLMhEucGF0Y2hlcy52MS5BY3RvchIPCgdwb3N0X2lkGAQgASgJEi4KCmNyZWF0ZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEisKB3JlYWRfYXQYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhcKD2NvbnZlcnNhdGlvbl9pZBgHIAEoCRIUCgxjb21tdW5pdHlfaWQYCCABKAkiOQoYTGlzdE5vdGlmaWNhdGlvbnNSZXF1ZXN0Eg4KBmN1cnNvchgBIAEoCRINCgVsaW1pdBgCIAEoDSJwChlMaXN0Tm90aWZpY2F0aW9uc1Jlc3BvbnNlEi8KDW5vdGlmaWNhdGlvbnMYASADKAsyGC5wYXRjaGVzLnYxLk5vdGlmaWNhdGlvbhIiCgRwYWdlGAIgASgLMhQucGF0Y2hlcy52MS5QYWdlSW5mbyJEChxNYXJrTm90aWZpY2F0aW9uc1JlYWRSZXF1ZXN0EhIKCnRocm91Z2hfaWQYASABKAkSEAoIbWFya19hbGwYAiABKAgiNQodTWFya05vdGlmaWNhdGlvbnNSZWFkUmVzcG9uc2USFAoMbWFya2VkX2NvdW50GAEgASgNIhcKFUdldFVucmVhZENvdW50UmVxdWVzdCInChZHZXRVbnJlYWRDb3VudFJlc3BvbnNlEg0KBWNvdW50GAEgASgNKvUCChBOb3RpZmljYXRpb25UeXBlEiEKHU5PVElGSUNBVElPTl9UWVBFX1VOU1BFQ0lGSUVEEAASHAoYTk9USUZJQ0FUSU9OX1RZUEVfRk9MTE9XEAESGgoWTk9USUZJQ0FUSU9OX1RZUEVfTElLRRACEhsKF05PVElGSUNBVElPTl9UWVBFX1JFUExZEAMSHQoZTk9USUZJQ0FUSU9OX1RZUEVfTUVOVElPThAEEiAKHE5PVElGSUNBVElPTl9UWVBFX01PREVSQVRJT04QBRIcChhOT1RJRklDQVRJT05fVFlQRV9SRVBPU1QQBhIbChdOT1RJRklDQVRJT05fVFlQRV9RVU9URRAHEh0KGU5PVElGSUNBVElPTl9UWVBFX01FU1NBR0UQCBImCiJOT1RJRklDQVRJT05fVFlQRV9DT01NVU5JVFlfSU5WSVRFEAkSJAogTk9USUZJQ0FUSU9OX1RZUEVfRk9MTE9XX1JFUVVFU1QQCjK+AgoTTm90aWZpY2F0aW9uU2VydmljZRJgChFMaXN0Tm90aWZpY2F0aW9ucxIkLnBhdGNoZXMudjEuTGlzdE5vdGlmaWNhdGlvbnNSZXF1ZXN0GiUucGF0Y2hlcy52MS5MaXN0Tm90aWZpY2F0aW9uc1Jlc3BvbnNlEmwKFU1hcmtOb3RpZmljYXRpb25zUmVhZBIoLnBhdGNoZXMudjEuTWFya05vdGlmaWNhdGlvbnNSZWFkUmVxdWVzdBopLnBhdGNoZXMudjEuTWFya05vdGlmaWNhdGlvbnNSZWFkUmVzcG9uc2USVwoOR2V0VW5yZWFkQ291bnQSIS5wYXRjaGVzLnYxLkdldFVucmVhZENvdW50UmVxdWVzdBoiLnBhdGNoZXMudjEuR2V0VW5yZWFkQ291bnRSZXNwb25zZWIGcHJvdG8z',
    [file_google_protobuf_timestamp, file_patches_v1_actors, file_patches_v1_common],
  );

/**
 * @generated from message patches.v1.Notification
 */
export type Notification = Message<'patches.v1.Notification'> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: patches.v1.NotificationType type = 2;
   */
  type: NotificationType;

  /**
   * The actor who triggered this notification (who liked/followed/replied/mentioned). Unset
   * for a MODERATION notification with no attributable actor.
   *
   * @generated from field: patches.v1.Actor actor = 3;
   */
  actor?: Actor | undefined;

  /**
   * Set for LIKE/REPLY/MENTION; empty for FOLLOW/MODERATION.
   *
   * @generated from field: string post_id = 4;
   */
  postId: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp | undefined;

  /**
   * Unset (zero value) while unread.
   *
   * @generated from field: google.protobuf.Timestamp read_at = 6;
   */
  readAt?: Timestamp | undefined;

  /**
   * Set for MESSAGE; empty otherwise. Never resolves to a message body — the caller must call
   * `DirectMessageService.ListMessages` for that.
   *
   * @generated from field: string conversation_id = 7;
   */
  conversationId: string;

  /**
   * Set for COMMUNITY_INVITE; empty otherwise.
   *
   * @generated from field: string community_id = 8;
   */
  communityId: string;
};

/**
 * Describes the message patches.v1.Notification.
 * Use `create(NotificationSchema)` to create a new message.
 */
export const NotificationSchema: GenMessage<Notification> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_notifications, 0);

/**
 * @generated from message patches.v1.ListNotificationsRequest
 */
export type ListNotificationsRequest = Message<'patches.v1.ListNotificationsRequest'> & {
  /**
   * @generated from field: string cursor = 1;
   */
  cursor: string;

  /**
   * @generated from field: uint32 limit = 2;
   */
  limit: number;
};

/**
 * Describes the message patches.v1.ListNotificationsRequest.
 * Use `create(ListNotificationsRequestSchema)` to create a new message.
 */
export const ListNotificationsRequestSchema: GenMessage<ListNotificationsRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_notifications, 1);

/**
 * @generated from message patches.v1.ListNotificationsResponse
 */
export type ListNotificationsResponse = Message<'patches.v1.ListNotificationsResponse'> & {
  /**
   * @generated from field: repeated patches.v1.Notification notifications = 1;
   */
  notifications: Notification[];

  /**
   * @generated from field: patches.v1.PageInfo page = 2;
   */
  page?: PageInfo | undefined;
};

/**
 * Describes the message patches.v1.ListNotificationsResponse.
 * Use `create(ListNotificationsResponseSchema)` to create a new message.
 */
export const ListNotificationsResponseSchema: GenMessage<ListNotificationsResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_notifications, 2);

/**
 * @generated from message patches.v1.MarkNotificationsReadRequest
 */
export type MarkNotificationsReadRequest = Message<'patches.v1.MarkNotificationsReadRequest'> & {
  /**
   * Marks every notification with this id or older (by the canonical created_at DESC, id DESC
   * ordering) as read. Ignored when `mark_all` is true.
   *
   * @generated from field: string through_id = 1;
   */
  throughId: string;

  /**
   * @generated from field: bool mark_all = 2;
   */
  markAll: boolean;
};

/**
 * Describes the message patches.v1.MarkNotificationsReadRequest.
 * Use `create(MarkNotificationsReadRequestSchema)` to create a new message.
 */
export const MarkNotificationsReadRequestSchema: GenMessage<MarkNotificationsReadRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_notifications, 3);

/**
 * @generated from message patches.v1.MarkNotificationsReadResponse
 */
export type MarkNotificationsReadResponse = Message<'patches.v1.MarkNotificationsReadResponse'> & {
  /**
   * @generated from field: uint32 marked_count = 1;
   */
  markedCount: number;
};

/**
 * Describes the message patches.v1.MarkNotificationsReadResponse.
 * Use `create(MarkNotificationsReadResponseSchema)` to create a new message.
 */
export const MarkNotificationsReadResponseSchema: GenMessage<MarkNotificationsReadResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_notifications, 4);

/**
 * @generated from message patches.v1.GetUnreadCountRequest
 */
export type GetUnreadCountRequest = Message<'patches.v1.GetUnreadCountRequest'> & {};

/**
 * Describes the message patches.v1.GetUnreadCountRequest.
 * Use `create(GetUnreadCountRequestSchema)` to create a new message.
 */
export const GetUnreadCountRequestSchema: GenMessage<GetUnreadCountRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_notifications, 5);

/**
 * @generated from message patches.v1.GetUnreadCountResponse
 */
export type GetUnreadCountResponse = Message<'patches.v1.GetUnreadCountResponse'> & {
  /**
   * @generated from field: uint32 count = 1;
   */
  count: number;
};

/**
 * Describes the message patches.v1.GetUnreadCountResponse.
 * Use `create(GetUnreadCountResponseSchema)` to create a new message.
 */
export const GetUnreadCountResponseSchema: GenMessage<GetUnreadCountResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_notifications, 6);

/**
 * @generated from enum patches.v1.NotificationType
 */
export enum NotificationType {
  /**
   * @generated from enum value: NOTIFICATION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: NOTIFICATION_TYPE_FOLLOW = 1;
   */
  FOLLOW = 1,

  /**
   * @generated from enum value: NOTIFICATION_TYPE_LIKE = 2;
   */
  LIKE = 2,

  /**
   * @generated from enum value: NOTIFICATION_TYPE_REPLY = 3;
   */
  REPLY = 3,

  /**
   * @generated from enum value: NOTIFICATION_TYPE_MENTION = 4;
   */
  MENTION = 4,

  /**
   * Reserved for moderator-initiated notices (e.g. "your post was removed"); no RPC creates
   * these yet — `ModerationService`'s admin-facing actions land with the admin CLI, spec §65.
   *
   * @generated from enum value: NOTIFICATION_TYPE_MODERATION = 5;
   */
  MODERATION = 5,

  /**
   * A repost of one of the caller's posts (spec §190).
   *
   * @generated from enum value: NOTIFICATION_TYPE_REPOST = 6;
   */
  REPOST = 6,

  /**
   * A quote of one of the caller's posts.
   *
   * @generated from enum value: NOTIFICATION_TYPE_QUOTE = 7;
   */
  QUOTE = 7,

  /**
   * A new direct message or message request landed. Never carries the message body — see
   * `Notification.conversation_id`.
   *
   * @generated from enum value: NOTIFICATION_TYPE_MESSAGE = 8;
   */
  MESSAGE = 8,

  /**
   * An invite to join a community.
   *
   * @generated from enum value: NOTIFICATION_TYPE_COMMUNITY_INVITE = 9;
   */
  COMMUNITY_INVITE = 9,

  /**
   * A follow request awaiting the caller's approval, because the caller's account is locked
   * (§197.5). Never fires for an ordinary follow of an unlocked account — that stays
   * `NOTIFICATION_TYPE_FOLLOW`, delivered once, on `AcceptFollowRequest`, not on request.
   *
   * @generated from enum value: NOTIFICATION_TYPE_FOLLOW_REQUEST = 10;
   */
  FOLLOW_REQUEST = 10,
}

/**
 * Describes the enum patches.v1.NotificationType.
 */
export const NotificationTypeSchema: GenEnum<NotificationType> =
  /*@__PURE__*/
  enumDesc(file_patches_v1_notifications, 0);

/**
 * Notification rows (spec §56, §113) — no separate event service. The TUI polls
 * `GetUnreadCount`/`ListNotifications` when active; there is no push infrastructure in v0.
 *
 * @generated from service patches.v1.NotificationService
 */
export const NotificationService: GenService<{
  /**
   * @generated from rpc patches.v1.NotificationService.ListNotifications
   */
  listNotifications: {
    methodKind: 'unary';
    input: typeof ListNotificationsRequestSchema;
    output: typeof ListNotificationsResponseSchema;
  };
  /**
   * Collapses spec §56's `MarkNotificationRead`/`MarkAllNotificationsRead` into one idempotent
   * RPC: marks every notification at or before `through_id` as read, or every notification
   * when `mark_all` is true. Marking an already-read notification again is not an error.
   *
   * @generated from rpc patches.v1.NotificationService.MarkNotificationsRead
   */
  markNotificationsRead: {
    methodKind: 'unary';
    input: typeof MarkNotificationsReadRequestSchema;
    output: typeof MarkNotificationsReadResponseSchema;
  };
  /**
   * @generated from rpc patches.v1.NotificationService.GetUnreadCount
   */
  getUnreadCount: {
    methodKind: 'unary';
    input: typeof GetUnreadCountRequestSchema;
    output: typeof GetUnreadCountResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_patches_v1_notifications, 0);
