// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file patches/v1/reactions.proto (package patches.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';
import type { Actor } from './actors_pb.js';
import { file_patches_v1_actors } from './actors_pb.js';
import type { PageInfo } from './common_pb.js';
import { file_patches_v1_common } from './common_pb.js';
import type { Post, PostCounts, PostViewerState } from './posts_pb.js';
import { file_patches_v1_posts } from './posts_pb.js';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file patches/v1/reactions.proto.
 */
export const file_patches_v1_reactions: GenFile =
  /*@__PURE__*/
  fileDesc(
    'ChpwYXRjaGVzL3YxL3JlYWN0aW9ucy5wcm90bxIKcGF0Y2hlcy52MSIiCg9MaWtlUG9zdFJlcXVlc3QSDwoHcG9zdF9pZBgBIAEoCSJtChBMaWtlUG9zdFJlc3BvbnNlEiYKBmNvdW50cxgBIAEoCzIWLnBhdGNoZXMudjEuUG9zdENvdW50cxIxCgx2aWV3ZXJfc3RhdGUYAiABKAsyGy5wYXRjaGVzLnYxLlBvc3RWaWV3ZXJTdGF0ZSIkChFVbmxpa2VQb3N0UmVxdWVzdBIPCgdwb3N0X2lkGAEgASgJIm8KElVubGlrZVBvc3RSZXNwb25zZRImCgZjb3VudHMYASABKAsyFi5wYXRjaGVzLnYxLlBvc3RDb3VudHMSMQoMdmlld2VyX3N0YXRlGAIgASgLMhsucGF0Y2hlcy52MS5Qb3N0Vmlld2VyU3RhdGUiJgoTQm9va21hcmtQb3N0UmVxdWVzdBIPCgdwb3N0X2lkGAEgASgJIkkKFEJvb2ttYXJrUG9zdFJlc3BvbnNlEjEKDHZpZXdlcl9zdGF0ZRgBIAEoCzIbLnBhdGNoZXMudjEuUG9zdFZpZXdlclN0YXRlIigKFVVuYm9va21hcmtQb3N0UmVxdWVzdBIPCgdwb3N0X2lkGAEgASgJIksKFlVuYm9va21hcmtQb3N0UmVzcG9uc2USMQoMdmlld2VyX3N0YXRlGAEgASgLMhsucGF0Y2hlcy52MS5Qb3N0Vmlld2VyU3RhdGUiNQoUTGlzdEJvb2ttYXJrc1JlcXVlc3QSDgoGY3Vyc29yGAEgASgJEg0KBWxpbWl0GAIgASgNIlwKFUxpc3RCb29rbWFya3NSZXNwb25zZRIfCgVwb3N0cxgBIAMoCzIQLnBhdGNoZXMudjEuUG9zdBIiCgRwYWdlGAIgASgLMhQucGF0Y2hlcy52MS5QYWdlSW5mbyJHChVMaXN0UG9zdExpa2Vyc1JlcXVlc3QSDwoHcG9zdF9pZBgBIAEoCRIOCgZjdXJzb3IYAiABKAkSDQoFbGltaXQYAyABKA0iXwoWTGlzdFBvc3RMaWtlcnNSZXNwb25zZRIhCgZhY3RvcnMYASADKAsyES5wYXRjaGVzLnYxLkFjdG9yEiIKBHBhZ2UYAiABKAsyFC5wYXRjaGVzLnYxLlBhZ2VJbmZvMoAECg9SZWFjdGlvblNlcnZpY2USRQoITGlrZVBvc3QSGy5wYXRjaGVzLnYxLkxpa2VQb3N0UmVxdWVzdBocLnBhdGNoZXMudjEuTGlrZVBvc3RSZXNwb25zZRJLCgpVbmxpa2VQb3N0Eh0ucGF0Y2hlcy52MS5Vbmxpa2VQb3N0UmVxdWVzdBoeLnBhdGNoZXMudjEuVW5saWtlUG9zdFJlc3BvbnNlElEKDEJvb2ttYXJrUG9zdBIfLnBhdGNoZXMudjEuQm9va21hcmtQb3N0UmVxdWVzdBogLnBhdGNoZXMudjEuQm9va21hcmtQb3N0UmVzcG9uc2USVwoOVW5ib29rbWFya1Bvc3QSIS5wYXRjaGVzLnYxLlVuYm9va21hcmtQb3N0UmVxdWVzdBoiLnBhdGNoZXMudjEuVW5ib29rbWFya1Bvc3RSZXNwb25zZRJUCg1MaXN0Qm9va21hcmtzEiAucGF0Y2hlcy52MS5MaXN0Qm9va21hcmtzUmVxdWVzdBohLnBhdGNoZXMudjEuTGlzdEJvb2ttYXJrc1Jlc3BvbnNlElcKDkxpc3RQb3N0TGlrZXJzEiEucGF0Y2hlcy52MS5MaXN0UG9zdExpa2Vyc1JlcXVlc3QaIi5wYXRjaGVzLnYxLkxpc3RQb3N0TGlrZXJzUmVzcG9uc2ViBnByb3RvMw',
    [file_patches_v1_actors, file_patches_v1_common, file_patches_v1_posts],
  );

/**
 * @generated from message patches.v1.LikePostRequest
 */
export type LikePostRequest = Message<'patches.v1.LikePostRequest'> & {
  /**
   * @generated from field: string post_id = 1;
   */
  postId: string;
};

/**
 * Describes the message patches.v1.LikePostRequest.
 * Use `create(LikePostRequestSchema)` to create a new message.
 */
export const LikePostRequestSchema: GenMessage<LikePostRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_reactions, 0);

/**
 * @generated from message patches.v1.LikePostResponse
 */
export type LikePostResponse = Message<'patches.v1.LikePostResponse'> & {
  /**
   * @generated from field: patches.v1.PostCounts counts = 1;
   */
  counts?: PostCounts | undefined;

  /**
   * @generated from field: patches.v1.PostViewerState viewer_state = 2;
   */
  viewerState?: PostViewerState | undefined;
};

/**
 * Describes the message patches.v1.LikePostResponse.
 * Use `create(LikePostResponseSchema)` to create a new message.
 */
export const LikePostResponseSchema: GenMessage<LikePostResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_reactions, 1);

/**
 * @generated from message patches.v1.UnlikePostRequest
 */
export type UnlikePostRequest = Message<'patches.v1.UnlikePostRequest'> & {
  /**
   * @generated from field: string post_id = 1;
   */
  postId: string;
};

/**
 * Describes the message patches.v1.UnlikePostRequest.
 * Use `create(UnlikePostRequestSchema)` to create a new message.
 */
export const UnlikePostRequestSchema: GenMessage<UnlikePostRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_reactions, 2);

/**
 * @generated from message patches.v1.UnlikePostResponse
 */
export type UnlikePostResponse = Message<'patches.v1.UnlikePostResponse'> & {
  /**
   * @generated from field: patches.v1.PostCounts counts = 1;
   */
  counts?: PostCounts | undefined;

  /**
   * @generated from field: patches.v1.PostViewerState viewer_state = 2;
   */
  viewerState?: PostViewerState | undefined;
};

/**
 * Describes the message patches.v1.UnlikePostResponse.
 * Use `create(UnlikePostResponseSchema)` to create a new message.
 */
export const UnlikePostResponseSchema: GenMessage<UnlikePostResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_reactions, 3);

/**
 * @generated from message patches.v1.BookmarkPostRequest
 */
export type BookmarkPostRequest = Message<'patches.v1.BookmarkPostRequest'> & {
  /**
   * @generated from field: string post_id = 1;
   */
  postId: string;
};

/**
 * Describes the message patches.v1.BookmarkPostRequest.
 * Use `create(BookmarkPostRequestSchema)` to create a new message.
 */
export const BookmarkPostRequestSchema: GenMessage<BookmarkPostRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_reactions, 4);

/**
 * @generated from message patches.v1.BookmarkPostResponse
 */
export type BookmarkPostResponse = Message<'patches.v1.BookmarkPostResponse'> & {
  /**
   * @generated from field: patches.v1.PostViewerState viewer_state = 1;
   */
  viewerState?: PostViewerState | undefined;
};

/**
 * Describes the message patches.v1.BookmarkPostResponse.
 * Use `create(BookmarkPostResponseSchema)` to create a new message.
 */
export const BookmarkPostResponseSchema: GenMessage<BookmarkPostResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_reactions, 5);

/**
 * @generated from message patches.v1.UnbookmarkPostRequest
 */
export type UnbookmarkPostRequest = Message<'patches.v1.UnbookmarkPostRequest'> & {
  /**
   * @generated from field: string post_id = 1;
   */
  postId: string;
};

/**
 * Describes the message patches.v1.UnbookmarkPostRequest.
 * Use `create(UnbookmarkPostRequestSchema)` to create a new message.
 */
export const UnbookmarkPostRequestSchema: GenMessage<UnbookmarkPostRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_reactions, 6);

/**
 * @generated from message patches.v1.UnbookmarkPostResponse
 */
export type UnbookmarkPostResponse = Message<'patches.v1.UnbookmarkPostResponse'> & {
  /**
   * @generated from field: patches.v1.PostViewerState viewer_state = 1;
   */
  viewerState?: PostViewerState | undefined;
};

/**
 * Describes the message patches.v1.UnbookmarkPostResponse.
 * Use `create(UnbookmarkPostResponseSchema)` to create a new message.
 */
export const UnbookmarkPostResponseSchema: GenMessage<UnbookmarkPostResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_reactions, 7);

/**
 * @generated from message patches.v1.ListBookmarksRequest
 */
export type ListBookmarksRequest = Message<'patches.v1.ListBookmarksRequest'> & {
  /**
   * @generated from field: string cursor = 1;
   */
  cursor: string;

  /**
   * @generated from field: uint32 limit = 2;
   */
  limit: number;
};

/**
 * Describes the message patches.v1.ListBookmarksRequest.
 * Use `create(ListBookmarksRequestSchema)` to create a new message.
 */
export const ListBookmarksRequestSchema: GenMessage<ListBookmarksRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_reactions, 8);

/**
 * @generated from message patches.v1.ListBookmarksResponse
 */
export type ListBookmarksResponse = Message<'patches.v1.ListBookmarksResponse'> & {
  /**
   * @generated from field: repeated patches.v1.Post posts = 1;
   */
  posts: Post[];

  /**
   * @generated from field: patches.v1.PageInfo page = 2;
   */
  page?: PageInfo | undefined;
};

/**
 * Describes the message patches.v1.ListBookmarksResponse.
 * Use `create(ListBookmarksResponseSchema)` to create a new message.
 */
export const ListBookmarksResponseSchema: GenMessage<ListBookmarksResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_reactions, 9);

/**
 * @generated from message patches.v1.ListPostLikersRequest
 */
export type ListPostLikersRequest = Message<'patches.v1.ListPostLikersRequest'> & {
  /**
   * @generated from field: string post_id = 1;
   */
  postId: string;

  /**
   * @generated from field: string cursor = 2;
   */
  cursor: string;

  /**
   * @generated from field: uint32 limit = 3;
   */
  limit: number;
};

/**
 * Describes the message patches.v1.ListPostLikersRequest.
 * Use `create(ListPostLikersRequestSchema)` to create a new message.
 */
export const ListPostLikersRequestSchema: GenMessage<ListPostLikersRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_reactions, 10);

/**
 * @generated from message patches.v1.ListPostLikersResponse
 */
export type ListPostLikersResponse = Message<'patches.v1.ListPostLikersResponse'> & {
  /**
   * @generated from field: repeated patches.v1.Actor actors = 1;
   */
  actors: Actor[];

  /**
   * @generated from field: patches.v1.PageInfo page = 2;
   */
  page?: PageInfo | undefined;
};

/**
 * Describes the message patches.v1.ListPostLikersResponse.
 * Use `create(ListPostLikersResponseSchema)` to create a new message.
 */
export const ListPostLikersResponseSchema: GenMessage<ListPostLikersResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_reactions, 11);

/**
 * Likes and bookmarks (spec §53). Bookmarks are private — never exposed on another actor's
 * view; `ListBookmarks` only ever returns the caller's own.
 *
 * @generated from service patches.v1.ReactionService
 */
export const ReactionService: GenService<{
  /**
   * @generated from rpc patches.v1.ReactionService.LikePost
   */
  likePost: {
    methodKind: 'unary';
    input: typeof LikePostRequestSchema;
    output: typeof LikePostResponseSchema;
  };
  /**
   * Idempotent: unliking a post the caller has not liked is not an error.
   *
   * @generated from rpc patches.v1.ReactionService.UnlikePost
   */
  unlikePost: {
    methodKind: 'unary';
    input: typeof UnlikePostRequestSchema;
    output: typeof UnlikePostResponseSchema;
  };
  /**
   * @generated from rpc patches.v1.ReactionService.BookmarkPost
   */
  bookmarkPost: {
    methodKind: 'unary';
    input: typeof BookmarkPostRequestSchema;
    output: typeof BookmarkPostResponseSchema;
  };
  /**
   * Idempotent: unbookmarking a post the caller has not bookmarked is not an error.
   *
   * @generated from rpc patches.v1.ReactionService.UnbookmarkPost
   */
  unbookmarkPost: {
    methodKind: 'unary';
    input: typeof UnbookmarkPostRequestSchema;
    output: typeof UnbookmarkPostResponseSchema;
  };
  /**
   * The caller's own bookmarks, most-recent first (spec §52 MVP note, §53). Requires an
   * authenticated session — there is no such thing as an anonymous bookmark list.
   *
   * @generated from rpc patches.v1.ReactionService.ListBookmarks
   */
  listBookmarks: {
    methodKind: 'unary';
    input: typeof ListBookmarksRequestSchema;
    output: typeof ListBookmarksResponseSchema;
  };
  /**
   * Actors who liked a post, most-recent first.
   *
   * @generated from rpc patches.v1.ReactionService.ListPostLikers
   */
  listPostLikers: {
    methodKind: 'unary';
    input: typeof ListPostLikersRequestSchema;
    output: typeof ListPostLikersResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_patches_v1_reactions, 0);
