// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file patches/v1/tags.proto (package patches.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';
import type { Timestamp } from '@bufbuild/protobuf/wkt';
import { file_google_protobuf_timestamp } from '@bufbuild/protobuf/wkt';
import type { PageInfo } from './common_pb.js';
import { file_patches_v1_common } from './common_pb.js';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file patches/v1/tags.proto.
 */
export const file_patches_v1_tags: GenFile =
  /*@__PURE__*/
  fileDesc(
    'ChVwYXRjaGVzL3YxL3RhZ3MucHJvdG8SCnBhdGNoZXMudjEiZQoDVGFnEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSFAoMZGlzcGxheV9uYW1lGAMgASgJEi4KCmNyZWF0ZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIkEKEVNlYXJjaFRhZ3NSZXF1ZXN0Eg0KBXF1ZXJ5GAEgASgJEg4KBmN1cnNvchgCIAEoCRINCgVsaW1pdBgDIAEoDSJXChJTZWFyY2hUYWdzUmVzcG9uc2USHQoEdGFncxgBIAMoCzIPLnBhdGNoZXMudjEuVGFnEiIKBHBhZ2UYAiABKAsyFC5wYXRjaGVzLnYxLlBhZ2VJbmZvIiAKDk11dGVUYWdSZXF1ZXN0Eg4KBnRhZ19pZBgBIAEoCSIRCg9NdXRlVGFnUmVzcG9uc2UiIgoQVW5tdXRlVGFnUmVxdWVzdBIOCgZ0YWdfaWQYASABKAkiEwoRVW5tdXRlVGFnUmVzcG9uc2UiNQoUTGlzdE11dGVkVGFnc1JlcXVlc3QSDgoGY3Vyc29yGAEgASgJEg0KBWxpbWl0GAIgASgNIloKFUxpc3RNdXRlZFRhZ3NSZXNwb25zZRIdCgR0YWdzGAEgAygLMg8ucGF0Y2hlcy52MS5UYWcSIgoEcGFnZRgCIAEoCzIULnBhdGNoZXMudjEuUGFnZUluZm8yvQIKClRhZ1NlcnZpY2USSwoKU2VhcmNoVGFncxIdLnBhdGNoZXMudjEuU2VhcmNoVGFnc1JlcXVlc3QaHi5wYXRjaGVzLnYxLlNlYXJjaFRhZ3NSZXNwb25zZRJCCgdNdXRlVGFnEhoucGF0Y2hlcy52MS5NdXRlVGFnUmVxdWVzdBobLnBhdGNoZXMudjEuTXV0ZVRhZ1Jlc3BvbnNlEkgKCVVubXV0ZVRhZxIcLnBhdGNoZXMudjEuVW5tdXRlVGFnUmVxdWVzdBodLnBhdGNoZXMudjEuVW5tdXRlVGFnUmVzcG9uc2USVAoNTGlzdE11dGVkVGFncxIgLnBhdGNoZXMudjEuTGlzdE11dGVkVGFnc1JlcXVlc3QaIS5wYXRjaGVzLnYxLkxpc3RNdXRlZFRhZ3NSZXNwb25zZWIGcHJvdG8z',
    [file_google_protobuf_timestamp, file_patches_v1_common],
  );

/**
 * @generated from message patches.v1.Tag
 */
export type Tag = Message<'patches.v1.Tag'> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Canonical form: NFKC-normalized and casefolded (spec §189, §192). Max 30 characters,
   * at least one letter (spec §188).
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * As originally cased by whoever first used it.
   *
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp | undefined;
};

/**
 * Describes the message patches.v1.Tag.
 * Use `create(TagSchema)` to create a new message.
 */
export const TagSchema: GenMessage<Tag> = /*@__PURE__*/ messageDesc(file_patches_v1_tags, 0);

/**
 * @generated from message patches.v1.SearchTagsRequest
 */
export type SearchTagsRequest = Message<'patches.v1.SearchTagsRequest'> & {
  /**
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * @generated from field: string cursor = 2;
   */
  cursor: string;

  /**
   * @generated from field: uint32 limit = 3;
   */
  limit: number;
};

/**
 * Describes the message patches.v1.SearchTagsRequest.
 * Use `create(SearchTagsRequestSchema)` to create a new message.
 */
export const SearchTagsRequestSchema: GenMessage<SearchTagsRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_tags, 1);

/**
 * @generated from message patches.v1.SearchTagsResponse
 */
export type SearchTagsResponse = Message<'patches.v1.SearchTagsResponse'> & {
  /**
   * @generated from field: repeated patches.v1.Tag tags = 1;
   */
  tags: Tag[];

  /**
   * @generated from field: patches.v1.PageInfo page = 2;
   */
  page?: PageInfo | undefined;
};

/**
 * Describes the message patches.v1.SearchTagsResponse.
 * Use `create(SearchTagsResponseSchema)` to create a new message.
 */
export const SearchTagsResponseSchema: GenMessage<SearchTagsResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_tags, 2);

/**
 * @generated from message patches.v1.MuteTagRequest
 */
export type MuteTagRequest = Message<'patches.v1.MuteTagRequest'> & {
  /**
   * @generated from field: string tag_id = 1;
   */
  tagId: string;
};

/**
 * Describes the message patches.v1.MuteTagRequest.
 * Use `create(MuteTagRequestSchema)` to create a new message.
 */
export const MuteTagRequestSchema: GenMessage<MuteTagRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_tags, 3);

/**
 * @generated from message patches.v1.MuteTagResponse
 */
export type MuteTagResponse = Message<'patches.v1.MuteTagResponse'> & {};

/**
 * Describes the message patches.v1.MuteTagResponse.
 * Use `create(MuteTagResponseSchema)` to create a new message.
 */
export const MuteTagResponseSchema: GenMessage<MuteTagResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_tags, 4);

/**
 * @generated from message patches.v1.UnmuteTagRequest
 */
export type UnmuteTagRequest = Message<'patches.v1.UnmuteTagRequest'> & {
  /**
   * @generated from field: string tag_id = 1;
   */
  tagId: string;
};

/**
 * Describes the message patches.v1.UnmuteTagRequest.
 * Use `create(UnmuteTagRequestSchema)` to create a new message.
 */
export const UnmuteTagRequestSchema: GenMessage<UnmuteTagRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_tags, 5);

/**
 * @generated from message patches.v1.UnmuteTagResponse
 */
export type UnmuteTagResponse = Message<'patches.v1.UnmuteTagResponse'> & {};

/**
 * Describes the message patches.v1.UnmuteTagResponse.
 * Use `create(UnmuteTagResponseSchema)` to create a new message.
 */
export const UnmuteTagResponseSchema: GenMessage<UnmuteTagResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_tags, 6);

/**
 * @generated from message patches.v1.ListMutedTagsRequest
 */
export type ListMutedTagsRequest = Message<'patches.v1.ListMutedTagsRequest'> & {
  /**
   * @generated from field: string cursor = 1;
   */
  cursor: string;

  /**
   * @generated from field: uint32 limit = 2;
   */
  limit: number;
};

/**
 * Describes the message patches.v1.ListMutedTagsRequest.
 * Use `create(ListMutedTagsRequestSchema)` to create a new message.
 */
export const ListMutedTagsRequestSchema: GenMessage<ListMutedTagsRequest> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_tags, 7);

/**
 * @generated from message patches.v1.ListMutedTagsResponse
 */
export type ListMutedTagsResponse = Message<'patches.v1.ListMutedTagsResponse'> & {
  /**
   * @generated from field: repeated patches.v1.Tag tags = 1;
   */
  tags: Tag[];

  /**
   * @generated from field: patches.v1.PageInfo page = 2;
   */
  page?: PageInfo | undefined;
};

/**
 * Describes the message patches.v1.ListMutedTagsResponse.
 * Use `create(ListMutedTagsResponseSchema)` to create a new message.
 */
export const ListMutedTagsResponseSchema: GenMessage<ListMutedTagsResponse> =
  /*@__PURE__*/
  messageDesc(file_patches_v1_tags, 8);

/**
 * Hashtag search and per-actor tag mutes (spec §189–190). Deliberately no post-count/
 * popularity surface anywhere in this service (spec §181, §58) — there is no engagement
 * ranking in this product and a tag's count is not published.
 *
 * @generated from service patches.v1.TagService
 */
export const TagService: GenService<{
  /**
   * Handle-prefix-style search over tag names (spec §112's search pattern, applied to tags).
   *
   * @generated from rpc patches.v1.TagService.SearchTags
   */
  searchTags: {
    methodKind: 'unary';
    input: typeof SearchTagsRequestSchema;
    output: typeof SearchTagsResponseSchema;
  };
  /**
   * Idempotent: muting an already-muted tag is not an error.
   *
   * @generated from rpc patches.v1.TagService.MuteTag
   */
  muteTag: {
    methodKind: 'unary';
    input: typeof MuteTagRequestSchema;
    output: typeof MuteTagResponseSchema;
  };
  /**
   * Idempotent: unmuting a tag the caller hasn't muted is not an error.
   *
   * @generated from rpc patches.v1.TagService.UnmuteTag
   */
  unmuteTag: {
    methodKind: 'unary';
    input: typeof UnmuteTagRequestSchema;
    output: typeof UnmuteTagResponseSchema;
  };
  /**
   * The caller's own muted tags, most-recent first.
   *
   * @generated from rpc patches.v1.TagService.ListMutedTags
   */
  listMutedTags: {
    methodKind: 'unary';
    input: typeof ListMutedTagsRequestSchema;
    output: typeof ListMutedTagsResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_patches_v1_tags, 0);
