import { Controller } from '@nestjs/common';
import {
  type GetServerInfoRequest,
  type GetServerInfoResponse,
  type PingRequest,
  type PingResponse,
  type SystemServiceController,
  SystemServiceControllerMethods,
} from '@patches/proto/nest';

import { SystemService } from './system.service.js';

/**
 * Transport adapter for `patches.v1.SystemService` — protobuf in, protobuf out,
 * no business logic (spec §128).
 *
 * `@SystemServiceControllerMethods()` is generated by ts-proto and applies
 * `@GrpcMethod` to every RPC declared in `system.proto`, so a new RPC in the
 * schema fails to compile here until it is implemented.
 */
@Controller()
@SystemServiceControllerMethods()
export class SystemController implements SystemServiceController {
  constructor(private readonly system: SystemService) {}

  getServerInfo(_request: GetServerInfoRequest): GetServerInfoResponse {
    return this.system.getServerInfo();
  }

  ping(request: PingRequest): PingResponse {
    return this.system.ping(request.nonce);
  }
}
