// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: patches/v1/common.proto
// Protobuf Java Version: 4.30.2

package patches.v1;

public final class Common {
  private Common() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Common.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PageInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:patches.v1.PageInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Opaque cursor for the next page. Empty when there is no next page.
     * </pre>
     *
     * <code>string next_cursor = 1 [json_name = "nextCursor"];</code>
     * @return The nextCursor.
     */
    java.lang.String getNextCursor();
    /**
     * <pre>
     * Opaque cursor for the next page. Empty when there is no next page.
     * </pre>
     *
     * <code>string next_cursor = 1 [json_name = "nextCursor"];</code>
     * @return The bytes for nextCursor.
     */
    com.google.protobuf.ByteString
        getNextCursorBytes();

    /**
     * <pre>
     * True when another page exists. Clients should key "load more" off this
     * rather than off `next_cursor` being non-empty.
     * </pre>
     *
     * <code>bool has_more = 2 [json_name = "hasMore"];</code>
     * @return The hasMore.
     */
    boolean getHasMore();
  }
  /**
   * <pre>
   * Cursor pagination envelope (spec §46).
   *
   * Patches never uses offset pagination for timelines. Every list RPC follows the
   * same shape:
   *
   * message ListXxxRequest {
   * // Opaque cursor from a previous response's `page.next_cursor`.
   * // Empty/absent means "start from the newest item".
   * string cursor = 1;
   * // Server clamps this to a sane maximum.
   * uint32 limit = 2;
   * }
   *
   * message ListXxxResponse {
   * repeated Xxx items = 1;
   * PageInfo page = 2;
   * }
   *
   * Canonical ordering is `created_at DESC, id DESC`. The cursor is generated by
   * the server and is opaque: clients must never construct or parse one.
   * </pre>
   *
   * Protobuf type {@code patches.v1.PageInfo}
   */
  public static final class PageInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:patches.v1.PageInfo)
      PageInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        PageInfo.class.getName());
    }
    // Use PageInfo.newBuilder() to construct.
    private PageInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PageInfo() {
      nextCursor_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return patches.v1.Common.internal_static_patches_v1_PageInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return patches.v1.Common.internal_static_patches_v1_PageInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              patches.v1.Common.PageInfo.class, patches.v1.Common.PageInfo.Builder.class);
    }

    public static final int NEXT_CURSOR_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nextCursor_ = "";
    /**
     * <pre>
     * Opaque cursor for the next page. Empty when there is no next page.
     * </pre>
     *
     * <code>string next_cursor = 1 [json_name = "nextCursor"];</code>
     * @return The nextCursor.
     */
    @java.lang.Override
    public java.lang.String getNextCursor() {
      java.lang.Object ref = nextCursor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextCursor_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Opaque cursor for the next page. Empty when there is no next page.
     * </pre>
     *
     * <code>string next_cursor = 1 [json_name = "nextCursor"];</code>
     * @return The bytes for nextCursor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNextCursorBytes() {
      java.lang.Object ref = nextCursor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextCursor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HAS_MORE_FIELD_NUMBER = 2;
    private boolean hasMore_ = false;
    /**
     * <pre>
     * True when another page exists. Clients should key "load more" off this
     * rather than off `next_cursor` being non-empty.
     * </pre>
     *
     * <code>bool has_more = 2 [json_name = "hasMore"];</code>
     * @return The hasMore.
     */
    @java.lang.Override
    public boolean getHasMore() {
      return hasMore_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nextCursor_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, nextCursor_);
      }
      if (hasMore_ != false) {
        output.writeBool(2, hasMore_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nextCursor_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, nextCursor_);
      }
      if (hasMore_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, hasMore_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof patches.v1.Common.PageInfo)) {
        return super.equals(obj);
      }
      patches.v1.Common.PageInfo other = (patches.v1.Common.PageInfo) obj;

      if (!getNextCursor()
          .equals(other.getNextCursor())) return false;
      if (getHasMore()
          != other.getHasMore()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NEXT_CURSOR_FIELD_NUMBER;
      hash = (53 * hash) + getNextCursor().hashCode();
      hash = (37 * hash) + HAS_MORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasMore());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static patches.v1.Common.PageInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static patches.v1.Common.PageInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static patches.v1.Common.PageInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static patches.v1.Common.PageInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static patches.v1.Common.PageInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static patches.v1.Common.PageInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static patches.v1.Common.PageInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static patches.v1.Common.PageInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static patches.v1.Common.PageInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static patches.v1.Common.PageInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static patches.v1.Common.PageInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static patches.v1.Common.PageInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(patches.v1.Common.PageInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Cursor pagination envelope (spec §46).
     *
     * Patches never uses offset pagination for timelines. Every list RPC follows the
     * same shape:
     *
     * message ListXxxRequest {
     * // Opaque cursor from a previous response's `page.next_cursor`.
     * // Empty/absent means "start from the newest item".
     * string cursor = 1;
     * // Server clamps this to a sane maximum.
     * uint32 limit = 2;
     * }
     *
     * message ListXxxResponse {
     * repeated Xxx items = 1;
     * PageInfo page = 2;
     * }
     *
     * Canonical ordering is `created_at DESC, id DESC`. The cursor is generated by
     * the server and is opaque: clients must never construct or parse one.
     * </pre>
     *
     * Protobuf type {@code patches.v1.PageInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:patches.v1.PageInfo)
        patches.v1.Common.PageInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return patches.v1.Common.internal_static_patches_v1_PageInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return patches.v1.Common.internal_static_patches_v1_PageInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                patches.v1.Common.PageInfo.class, patches.v1.Common.PageInfo.Builder.class);
      }

      // Construct using patches.v1.Common.PageInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nextCursor_ = "";
        hasMore_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return patches.v1.Common.internal_static_patches_v1_PageInfo_descriptor;
      }

      @java.lang.Override
      public patches.v1.Common.PageInfo getDefaultInstanceForType() {
        return patches.v1.Common.PageInfo.getDefaultInstance();
      }

      @java.lang.Override
      public patches.v1.Common.PageInfo build() {
        patches.v1.Common.PageInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public patches.v1.Common.PageInfo buildPartial() {
        patches.v1.Common.PageInfo result = new patches.v1.Common.PageInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(patches.v1.Common.PageInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nextCursor_ = nextCursor_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.hasMore_ = hasMore_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof patches.v1.Common.PageInfo) {
          return mergeFrom((patches.v1.Common.PageInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(patches.v1.Common.PageInfo other) {
        if (other == patches.v1.Common.PageInfo.getDefaultInstance()) return this;
        if (!other.getNextCursor().isEmpty()) {
          nextCursor_ = other.nextCursor_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getHasMore() != false) {
          setHasMore(other.getHasMore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nextCursor_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                hasMore_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nextCursor_ = "";
      /**
       * <pre>
       * Opaque cursor for the next page. Empty when there is no next page.
       * </pre>
       *
       * <code>string next_cursor = 1 [json_name = "nextCursor"];</code>
       * @return The nextCursor.
       */
      public java.lang.String getNextCursor() {
        java.lang.Object ref = nextCursor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nextCursor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Opaque cursor for the next page. Empty when there is no next page.
       * </pre>
       *
       * <code>string next_cursor = 1 [json_name = "nextCursor"];</code>
       * @return The bytes for nextCursor.
       */
      public com.google.protobuf.ByteString
          getNextCursorBytes() {
        java.lang.Object ref = nextCursor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nextCursor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Opaque cursor for the next page. Empty when there is no next page.
       * </pre>
       *
       * <code>string next_cursor = 1 [json_name = "nextCursor"];</code>
       * @param value The nextCursor to set.
       * @return This builder for chaining.
       */
      public Builder setNextCursor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nextCursor_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Opaque cursor for the next page. Empty when there is no next page.
       * </pre>
       *
       * <code>string next_cursor = 1 [json_name = "nextCursor"];</code>
       * @return This builder for chaining.
       */
      public Builder clearNextCursor() {
        nextCursor_ = getDefaultInstance().getNextCursor();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Opaque cursor for the next page. Empty when there is no next page.
       * </pre>
       *
       * <code>string next_cursor = 1 [json_name = "nextCursor"];</code>
       * @param value The bytes for nextCursor to set.
       * @return This builder for chaining.
       */
      public Builder setNextCursorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nextCursor_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean hasMore_ ;
      /**
       * <pre>
       * True when another page exists. Clients should key "load more" off this
       * rather than off `next_cursor` being non-empty.
       * </pre>
       *
       * <code>bool has_more = 2 [json_name = "hasMore"];</code>
       * @return The hasMore.
       */
      @java.lang.Override
      public boolean getHasMore() {
        return hasMore_;
      }
      /**
       * <pre>
       * True when another page exists. Clients should key "load more" off this
       * rather than off `next_cursor` being non-empty.
       * </pre>
       *
       * <code>bool has_more = 2 [json_name = "hasMore"];</code>
       * @param value The hasMore to set.
       * @return This builder for chaining.
       */
      public Builder setHasMore(boolean value) {

        hasMore_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * True when another page exists. Clients should key "load more" off this
       * rather than off `next_cursor` being non-empty.
       * </pre>
       *
       * <code>bool has_more = 2 [json_name = "hasMore"];</code>
       * @return This builder for chaining.
       */
      public Builder clearHasMore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hasMore_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:patches.v1.PageInfo)
    }

    // @@protoc_insertion_point(class_scope:patches.v1.PageInfo)
    private static final patches.v1.Common.PageInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new patches.v1.Common.PageInfo();
    }

    public static patches.v1.Common.PageInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PageInfo>
        PARSER = new com.google.protobuf.AbstractParser<PageInfo>() {
      @java.lang.Override
      public PageInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PageInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PageInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public patches.v1.Common.PageInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patches_v1_PageInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_patches_v1_PageInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027patches/v1/common.proto\022\npatches.v1\"F\n" +
      "\010PageInfo\022\037\n\013next_cursor\030\001 \001(\tR\nnextCurs" +
      "or\022\031\n\010has_more\030\002 \001(\010R\007hasMoreb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_patches_v1_PageInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_patches_v1_PageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_patches_v1_PageInfo_descriptor,
        new java.lang.String[] { "NextCursor", "HasMore", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
