import { Injectable } from '@nestjs/common';
import { InjectDataSource } from '@nestjs/typeorm';
import {
  Actor,
  Block,
  Mute,
  Notification,
  Post,
  type NotificationType as DbNotificationType,
} from '@patches/database';
import { DataSource, IsNull } from 'typeorm';

import { AppError } from '../../common/errors/app-error.js';
import { toActorSummary } from '../auth/auth.dto.js';
import { applyActorHidePushdown, MAX_FILTER_ROUNDS } from '../feeds/feed.service.js';
import { clampLimit, decodeCursor, pageInfoFor } from '../feeds/pagination.js';
import {
  buildFilterMatchCandidates,
  evaluateCandidate,
  loadEffectiveFilterRules,
  type FilterMatchCandidate,
} from '../filters/filter-matching.js';
import { parseInput, uuidInputSchema } from '../posts/validation.js';
import type { NotificationView } from './notification.dto.js';

/**
 * The application service behind `patches.v1.NotificationService` (spec §56, §113).
 *
 * `notifyFollow`/`notifyLike`/`notifyReply`/`notifyMention` are the write side, called from
 * other feature services (`ReactionsService`, `PostService`, and — once `GraphModule` wires it
 * in, see this task's report — `GraphService.followActor`) rather than exposed as their own
 * RPCs; spec §113 has "no separate event service", just rows created as a side effect of the
 * action that causes them.
 */

export interface ListNotificationsResult {
  notifications: NotificationView[];
  nextCursor: string;
  hasMore: boolean;
}

@Injectable()
export class NotificationsService {
  constructor(@InjectDataSource() private readonly dataSource: DataSource) {}

  /**
   * A-051 (spec §198.3): `NOTIFICATIONS`-scope `hide` rules omit notifications generated by a
   * matching actor/post server-side, the same bounded-over-fetch chokepoint
   * `FeedService`/`PostService.searchPosts` use (`FeedService.MAX_FILTER_ROUNDS`) — a `hide`
   * match must never leave the page short just because a round's rows were all hidden, but the
   * re-fetching MUST stay bounded (§198.4). Only `hide` is enforced here: `collapse`/`warn`
   * have no notification-list UI to attach a `filtered_by` hint to, so those actions are a
   * silent no-op for this scope (documented on `FilterScope.NOTIFICATIONS` in
   * `filter-enums.ts`).
   */
  async listNotifications(
    recipientActorId: string,
    cursorRaw: string,
    limit: number,
  ): Promise<ListNotificationsResult> {
    const take = clampLimit(limit);
    let cursor = decodeCursor(cursorRaw);

    const rules = await loadEffectiveFilterRules(
      this.dataSource,
      recipientActorId,
      'NOTIFICATIONS',
    );

    const collected: Array<Notification & { actor: Actor | null }> = [];
    let roundHasMore = false;
    for (let round = 0; round < MAX_FILTER_ROUNDS && collected.length < take; round += 1) {
      const remaining = take - collected.length;
      const qb = this.dataSource
        .getRepository(Notification)
        .createQueryBuilder('notification')
        .leftJoinAndSelect('notification.actor', 'actor')
        .leftJoinAndSelect('notification.post', 'post')
        .where('notification.recipientActorId = :recipientActorId', { recipientActorId })
        .orderBy('notification.createdAt', 'DESC')
        .addOrderBy('notification.id', 'DESC');
      // P14-021-style pushdown: a `hide`-action ACTOR rule excludes rows by the triggering
      // actor ahead of the round loop — a pure performance win, never a correctness dependency
      // (the in-process `evaluateCandidate` below still re-checks every row).
      applyActorHidePushdown(qb, rules, '"notification"."actor_id"', 'notificationHideActorIds');
      if (cursor !== undefined) {
        qb.andWhere('(notification.createdAt, notification.id) < (:cursorCreatedAt, :cursorId)', {
          cursorCreatedAt: cursor.createdAt,
          cursorId: cursor.id,
        });
      }
      qb.take(remaining + 1);

      const rows = await qb.getMany();
      roundHasMore = rows.length > remaining;
      const roundRows = roundHasMore ? rows.slice(0, remaining) : rows;
      if (roundRows.length === 0) break;

      if (rules.length === 0) {
        collected.push(...roundRows);
      } else {
        const candidates = await buildNotificationFilterCandidates(this.dataSource, roundRows);
        for (const row of roundRows) {
          const candidate = candidates.get(row.id);
          const match = candidate === undefined ? null : evaluateCandidate(rules, candidate);
          if (match?.action === 'HIDE') continue;
          collected.push(row);
        }
      }

      const last = roundRows.at(-1);
      if (last !== undefined) cursor = { createdAt: last.createdAt, id: last.id };
      if (!roundHasMore) break;
    }

    const page = collected.slice(0, take);
    const notifications = page.map((row) => toNotificationView(row));
    const { nextCursor } = pageInfoFor(page, roundHasMore, (row) => ({
      createdAt: row.createdAt,
      id: row.id,
    }));
    return { notifications, nextCursor, hasMore: roundHasMore };
  }

  /**
   * `markAll` marks every unread notification for the caller; otherwise `throughIdRaw` must
   * name one of the caller's own notifications and every notification at or before it (by the
   * canonical `created_at DESC, id DESC` ordering) is marked read. Idempotent either way —
   * re-marking an already-read notification is not an error, just a no-op row.
   */
  async markNotificationsRead(
    recipientActorId: string,
    throughIdRaw: string,
    markAll: boolean,
  ): Promise<number> {
    const notifications = this.dataSource.getRepository(Notification);

    if (markAll) {
      const result = await notifications
        .createQueryBuilder()
        .update(Notification)
        .set({ readAt: new Date() })
        .where('recipient_actor_id = :recipientActorId', { recipientActorId })
        .andWhere('read_at IS NULL')
        .execute();
      return result.affected ?? 0;
    }

    const throughId = parseInput(uuidInputSchema, throughIdRaw);
    const throughRow = await notifications.findOne({
      where: { id: throughId, recipientActorId },
    });
    if (throughRow === null) {
      throw AppError.validation('through_id must reference one of your own notifications.');
    }

    const result = await notifications
      .createQueryBuilder()
      .update(Notification)
      .set({ readAt: new Date() })
      .where('recipient_actor_id = :recipientActorId', { recipientActorId })
      .andWhere('read_at IS NULL')
      .andWhere('(created_at, id) <= (:throughCreatedAt, :throughId)', {
        throughCreatedAt: throughRow.createdAt,
        throughId,
      })
      .execute();
    return result.affected ?? 0;
  }

  getUnreadCount(recipientActorId: string): Promise<number> {
    return this.dataSource
      .getRepository(Notification)
      .countBy({ recipientActorId, readAt: IsNull() });
  }

  async notifyFollow(recipientActorId: string, actorId: string): Promise<void> {
    await this.create('FOLLOW', recipientActorId, actorId, {});
  }

  /** §197.5: a follow request awaiting the recipient's approval, because the recipient's
   * account is locked. Distinct from `notifyFollow`, which `GraphService.acceptFollowRequest`
   * calls (addressed to the *requester*, not the locked actor) once the request is accepted —
   * this one is written once, when the request is first created. */
  async notifyFollowRequest(recipientActorId: string, actorId: string): Promise<void> {
    await this.create('FOLLOW_REQUEST', recipientActorId, actorId, {});
  }

  async notifyLike(recipientActorId: string, actorId: string, postId: string): Promise<void> {
    await this.create('LIKE', recipientActorId, actorId, { postId });
  }

  async notifyReply(recipientActorId: string, actorId: string, postId: string): Promise<void> {
    await this.create('REPLY', recipientActorId, actorId, { postId });
  }

  async notifyMention(recipientActorId: string, actorId: string, postId: string): Promise<void> {
    await this.create('MENTION', recipientActorId, actorId, { postId });
  }

  async notifyRepost(recipientActorId: string, actorId: string, postId: string): Promise<void> {
    await this.create('REPOST', recipientActorId, actorId, { postId });
  }

  async notifyQuote(recipientActorId: string, actorId: string, postId: string): Promise<void> {
    await this.create('QUOTE', recipientActorId, actorId, { postId });
  }

  async notifyMessage(
    recipientActorId: string,
    actorId: string,
    conversationId: string | null,
  ): Promise<void> {
    await this.create(
      'MESSAGE',
      recipientActorId,
      actorId,
      conversationId === null ? {} : { conversationId },
    );
  }

  async notifyCommunityInvite(
    recipientActorId: string,
    actorId: string,
    communityId: string,
  ): Promise<void> {
    await this.create('COMMUNITY_INVITE', recipientActorId, actorId, { communityId });
  }

  // ---------------------------------------------------------------- internals

  /**
   * Common write path for every notify* method above. Never notifies the actor about their own
   * action, and respects blocks (§62) and mutes (§63) in both directions before ever inserting
   * a row — the caller does not have to know those rules.
   */
  private async create(
    type: DbNotificationType,
    recipientActorId: string,
    actorId: string,
    target: { postId?: string; conversationId?: string; communityId?: string },
  ): Promise<void> {
    if (recipientActorId === actorId) return;
    if (await this.blockedEitherDirection(recipientActorId, actorId)) return;
    if (await this.muted(recipientActorId, actorId)) return;

    const notifications = this.dataSource.getRepository(Notification);
    try {
      await notifications.save(
        notifications.create({
          recipientActorId,
          type,
          actorId,
          postId: target.postId ?? null,
          conversationId: target.conversationId ?? null,
          communityId: target.communityId ?? null,
        }),
      );
    } catch (error) {
      // The `Notification` entity's two partial unique indexes are the dedupe backstop (§113)
      // — a duplicate of an existing (recipient, type, actor, post) row is not an error, it is
      // exactly what "a retry must not produce a second notification" requires.
      if (!isUniqueViolation(error)) throw error;
    }
  }

  private async blockedEitherDirection(actorAId: string, actorBId: string): Promise<boolean> {
    const blocks = this.dataSource.getRepository(Block);
    const [aBlocksB, bBlocksA] = await Promise.all([
      blocks.findOne({ where: { blockerActorId: actorAId, blockedActorId: actorBId } }),
      blocks.findOne({ where: { blockerActorId: actorBId, blockedActorId: actorAId } }),
    ]);
    return aBlocksB !== null || bBlocksA !== null;
  }

  private async muted(recipientActorId: string, actorId: string): Promise<boolean> {
    const mute = await this.dataSource
      .getRepository(Mute)
      .findOne({ where: { muterActorId: recipientActorId, mutedActorId: actorId } });
    return mute !== null;
  }
}

/**
 * Builds one {@link FilterMatchCandidate} per notification for the A-051 chokepoint above.
 * `authorActorId` is always the *triggering* actor (`notification.actorId` — who liked/
 * followed/replied/mentioned, per the `Notification` entity's own doc comment), never the
 * recipient, so an `ACTOR` rule matches "hide notifications from this actor" regardless of
 * notification type. Post-content kinds (`SUBSTRING`/`WORD`/`TAG`/`DOMAIN`) only apply when the
 * attached post was *authored by that same triggering actor* — true for REPLY/MENTION/QUOTE
 * (the actor's own new post) but not LIKE/REPOST (whose `postId` is the recipient's own post
 * being liked/reposted); matching a viewer's own filters against their own content would be
 * nonsensical, so those notifications only ever hide on an `ACTOR` match.
 */
async function buildNotificationFilterCandidates(
  dataSource: DataSource,
  rows: readonly (Notification & { post: Post | null })[],
): Promise<Map<string, FilterMatchCandidate>> {
  const contentEligiblePosts = rows
    .filter(
      (row) => row.post !== null && row.actorId !== null && row.post.authorActorId === row.actorId,
    )
    .map((row) => row.post as Post);
  const postCandidates = await buildFilterMatchCandidates(dataSource, contentEligiblePosts);

  const candidates = new Map<string, FilterMatchCandidate>();
  for (const row of rows) {
    const postCandidate = row.post === null ? undefined : postCandidates.get(row.post.id);
    candidates.set(row.id, {
      id: row.id,
      authorActorId: row.actorId ?? '',
      quotedAuthorActorId: null,
      reposterActorIds: [],
      body: postCandidate?.body ?? null,
      contentWarning: postCandidate?.contentWarning ?? null,
      altTexts: postCandidate?.altTexts ?? [],
      linkUrl: postCandidate?.linkUrl ?? null,
      tagNames: postCandidate?.tagNames ?? [],
    });
  }
  return candidates;
}

function toNotificationView(row: Notification & { actor: Actor | null }): NotificationView {
  return {
    id: row.id,
    type: row.type,
    actor: row.actor === null ? null : toActorSummary(row.actor),
    postId: row.postId,
    conversationId: row.conversationId,
    communityId: row.communityId,
    createdAt: row.createdAt,
    readAt: row.readAt,
  };
}

/** PostgreSQL's `unique_violation` SQLSTATE, surfaced by `pg` as a plain `{ code: string }` —
 * same helper `PostService.createPost`/`GraphService.followActor` use for their own
 * idempotency races. */
function isUniqueViolation(error: unknown): boolean {
  return (
    typeof error === 'object' &&
    error !== null &&
    'code' in error &&
    (error as { code?: unknown }).code === '23505'
  );
}
